"""Agent runtime events for integrations.

Provides:
- ``resolve_events`` — layered event resolution (CLI flag → YAML override → extension-declared → built-in).
- ``collect_extension_events`` — scan installed extension.yml files for ``events:``.
- ``install_integration_events`` / ``remove_integration_events`` — entry points called from ``IntegrationBase.setup()`` / ``teardown()``.
"""

from __future__ import annotations

import json
import logging
import re
import sys
import subprocess
import platform
from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml

if TYPE_CHECKING:
    from .integrations.base import IntegrationBase
    from .integrations.manifest import IntegrationManifest

logger = logging.getLogger(__name__)

# -- Constants -------------------------------------------------------------

EVENTS_DISPATCHER_DIR = Path(".specify")
EVENTS_DISPATCHER_FILENAME = "events.py"
EVENTS_DISPATCHER_REL = str(EVENTS_DISPATCHER_DIR / EVENTS_DISPATCHER_FILENAME)

YAML_OVERRIDE_FILENAME = Path(".specify") / "integration-events.yml"

_SPECKIT_MARKER = "__speckit_event__"

# Canonical event names (snake_case)
CANONICAL_EVENTS = frozenset({
    "session_start",
    "pre_tool_use",
    "post_tool_use",
    "session_end",
    "user_prompt_submit",
    "stop",
})

# -- Events Dispatcher template ---------------------------------------------

_EVENTS_DISPATCHER_TEMPLATE = '''#!/usr/bin/env python3
"""Specify CLI Event Dispatcher — dispatches agent runtime events.

Generated by: specify integration install/upgrade
Do not edit manually.
"""
import sys, subprocess, os
from pathlib import Path


def _find_specify():
    project_root = Path(__file__).parent.parent.resolve()
    # 1. Check local virtualenv
    for candidate in ("venv", ".venv"):
        py_bin = project_root / candidate / "bin" / "specify"
        if py_bin.exists():
            return [str(py_bin)]
        # Windows virtualenv
        win_bin = project_root / candidate / "Scripts" / "specify.exe"
        if win_bin.exists():
            return [str(win_bin)]

    # 2. Check python -m specify_cli
    for candidate in ("venv", ".venv"):
        py_exe = project_root / candidate / "bin" / "python"
        if py_exe.exists():
            return [str(py_exe), "-m", "specify_cli"]
        win_py = project_root / candidate / "Scripts" / "python.exe"
        if win_py.exists():
            return [str(win_py), "-m", "specify_cli"]

    # 3. Fallback to system path specify
    return ["specify"]


def main():
    if len(sys.argv) < 3:
        sys.exit(0)
    command_name = sys.argv[1]
    event_name = sys.argv[2]
    payload = sys.stdin.read() if not sys.stdin.isatty() else "{}"

    specify_args = _find_specify() + ["event", "run", command_name, event_name]
    try:
        result = subprocess.run(
            specify_args,
            input=payload,
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.stdout:
            sys.stdout.write(result.stdout)
        if result.returncode != 0:
            if result.stderr:
                sys.stderr.write(result.stderr)
            sys.exit(result.returncode)
        sys.exit(0)
    except subprocess.TimeoutExpired:
        print(f"Event {command_name} timed out", file=sys.stderr)
        sys.exit(2)
    except Exception as e:
        print(f"Event {command_name} error: {e}", file=sys.stderr)
        sys.exit(2)


if __name__ == "__main__":
    main()
'''

# -- TS plugin template (opencode) ----------------------------------------

_TS_PLUGIN_TEMPLATE = '''import {{ execSync }} from 'child_process';
import * as path from 'path';

const DISPATCHER = path.join(process.cwd(), '.specify', 'events.py');

function runEvent(command: string, event: string, input: any): void {{
  try {{
    execSync(`python3 ${{DISPATCHER}} ${{command}} ${{event}}`, {{
      input: JSON.stringify(input),
      stdio: ['pipe', 'inherit', 'inherit'],
      timeout: 60000,
    }});
  }} catch (e) {{
    process.exit(2);
  }}
}}

{event_entries}

export default (async ({{ client, project, directory, $ }}) => {{
  return {{
{plugin_returns}
  }};
}});
'''


# -- Command runner logic (core) --------------------------------------------

def _find_command_template(command_name: str, project_root: Path) -> tuple[Path | None, str | None]:
    # 1. Check extension .registry
    registry = project_root / ".specify" / "extensions" / ".registry"
    if registry.exists():
        try:
            data = json.loads(registry.read_text(encoding="utf-8"))
        except Exception:
            data = {}
        for ext_id, meta in data.items():
            if not isinstance(meta, dict):
                continue
            for cmd in meta.get("commands", []):
                if cmd.get("name") == command_name:
                    ext_dir = project_root / ".specify" / "extensions" / ext_id
                    return ext_dir / cmd["file"], ext_id

    # 2. Scan extension directories
    exts_dir = project_root / ".specify" / "extensions"
    if exts_dir.is_dir():
        for ext_dir in sorted(exts_dir.iterdir()):
            cmds_dir = ext_dir / "commands"
            if cmds_dir.is_dir():
                for f in cmds_dir.glob("*.md"):
                    if f.stem == command_name:
                        return f, ext_dir.name

    # 3. Check core templates
    core = project_root / ".specify" / "templates" / "commands"
    if core.is_dir():
        stem = command_name.replace("speckit.", "").replace("spec.", "")
        candidate = core / f"{stem}.md"
        if candidate.exists():
            return candidate, None

    # Fallback to package bundled templates
    try:
        import inspect
        pkg_dir = Path(inspect.getfile(validate_events)).resolve().parent
        core_pack = pkg_dir / "core_pack" / "templates" / "commands"
        if core_pack.is_dir():
            stem = command_name.replace("speckit.", "").replace("spec.", "")
            candidate = core_pack / f"{stem}.md"
            if candidate.exists():
                return candidate, None
    except Exception:
        pass

    return None, None


def _extract_script_path(template_path: Path, project_root: Path, ext_id: str | None) -> str | None:
    content = template_path.read_text(encoding="utf-8")
    m = re.match(r'^---\n(.*?)\n---', content, re.DOTALL)
    if not m:
        return None
    fm = m.group(1)
    try:
        fm_data = yaml.safe_load(fm) or {}
    except Exception:
        return None
    if not isinstance(fm_data, dict):
        return None
    scripts = fm_data.get("scripts", {})
    if not isinstance(scripts, dict):
        return None
    default = "ps" if platform.system().lower().startswith("win") else "sh"
    script_rel = scripts.get(default) or scripts.get("sh") or scripts.get("py")
    if not script_rel:
        return None
    if ext_id:
        script_abs = project_root / ".specify" / "extensions" / ext_id / script_rel
    else:
        script_abs = project_root / ".specify" / script_rel
    return str(script_abs) if script_abs.exists() else None


def resolve_and_run_event_command(command_name: str, event_name: str, payload: str, project_root: Path) -> int:
    """Core entry point to resolve and execute an event-driven command."""
    template_path, ext_id = _find_command_template(command_name, project_root)
    if not template_path:
        logger.warning("Event command '%s' not found", command_name)
        return 0
    script_path = _extract_script_path(template_path, project_root, ext_id)
    if not script_path:
        logger.warning("No script found for event command '%s'", command_name)
        return 0
    try:
        result = subprocess.run(
            [script_path],
            input=payload,
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.stdout:
            sys.stdout.write(result.stdout)
        if result.returncode != 0:
            if result.stderr:
                sys.stderr.write(result.stderr)
            return result.returncode
        return 0
    except subprocess.TimeoutExpired:
        sys.stderr.write(f"Event command {command_name} timed out\n")
        return 2
    except Exception as e:
        sys.stderr.write(f"Event command {command_name} error: {e}\n")
        return 2


# -- Sourcing events map (CLI/Orchestration domain) -------------------------

def resolve_events(
    integration_key: str,
    integration_config: dict[str, Any] | None,
    project_root: Path,
    parsed_options: dict[str, Any] | None,
) -> dict[str, dict[str, Any]]:
    """Resolve the final event set for an integration."""
    # Layer 1: CLI flag gate
    if parsed_options:
        events_flag = str(parsed_options.get("events", "true")).lower()
        if events_flag in ("false", "0", "no", "off"):
            return {}

    # Layer 4: built-in defaults from integration config
    events: dict[str, dict[str, Any]] = {}
    if integration_config and isinstance(integration_config.get("events"), dict):
        events = dict(integration_config["events"])

    # Layer 3: extension-declared events
    ext_events = collect_extension_events(project_root)
    events.update(ext_events)

    # Layer 2: user YAML override (replaces entirely if key present)
    override_file = project_root / YAML_OVERRIDE_FILENAME
    if override_file.exists():
        try:
            override = yaml.safe_load(override_file.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError:
            logger.warning("Could not parse %s; ignoring override", override_file)
            override = {}
        integrations = override.get("integrations", {}) if isinstance(override, dict) else {}
        if integration_key in integrations:
            key_data = integrations[integration_key]
            if isinstance(key_data, dict):
                events = key_data.get("events", {}) or {}
            else:
                events = {}

    return events


def collect_extension_events(project_root: Path) -> dict[str, dict[str, Any]]:
    """Scan all installed extensions for ``events:`` declarations."""
    events: dict[str, dict[str, Any]] = {}
    exts_dir = project_root / ".specify" / "extensions"
    if not exts_dir.is_dir():
        return events

    for ext_dir in sorted(exts_dir.iterdir()):
        if not ext_dir.is_dir():
            continue
        ext_yml = ext_dir / "extension.yml"
        if not ext_yml.exists():
            continue
        try:
            data = yaml.safe_load(ext_yml.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError:
            continue
        if not isinstance(data, dict):
            continue
        runtime = data.get("events", {}) or {}
        if not isinstance(runtime, dict):
            continue
        for event, config in runtime.items():
            if isinstance(config, dict):
                events[event] = config
    return events


# -- Writing/Merging Config (Integration domain) ---------------------------

def install_integration_events(
    integration: IntegrationBase,
    project_root: Path,
    manifest: IntegrationManifest,
    events: dict[str, dict[str, Any]],
) -> list[Path]:
    """Generate dispatcher, merge native config, return created files."""
    canonical_to_native = getattr(integration, "CANONICAL_TO_NATIVE", {})
    if not canonical_to_native:
        return []

    # Filter to only supported events
    filtered: dict[str, dict[str, Any]] = {}
    for ev, cfg in events.items():
        if ev in canonical_to_native:
            filtered[ev] = cfg
        else:
            print(
                f"\u26a0\ufe0f  {integration.key} does not support '{ev}' events; skipping",
                file=sys.stderr,
            )

    if not filtered:
        return []

    created: list[Path] = []

    # 1. Generate events.py dispatcher script
    dispatcher_dir = project_root / EVENTS_DISPATCHER_DIR
    dispatcher_dir.mkdir(parents=True, exist_ok=True)
    dispatcher_path = dispatcher_dir / EVENTS_DISPATCHER_FILENAME
    dispatcher_path.write_text(_EVENTS_DISPATCHER_TEMPLATE, encoding="utf-8")
    dispatcher_path.chmod(0o755)
    manifest.record_file(
        str(dispatcher_path.relative_to(project_root)),
        dispatcher_path.read_bytes(),
    )
    created.append(dispatcher_path)

    # 2. Format-specific merge/write
    fmt = getattr(integration, "events_format", "json-nested")
    config_file = getattr(integration, "events_config_file", None)
    if not config_file:
        return created

    config_path = project_root / config_file

    if fmt == "ts-plugin":
        # Opencode TS plugin custom merge
        plugin_rel = ".opencode/plugin/speckit-events.ts"
        plugin_path = project_root / plugin_rel
        plugin_path.parent.mkdir(parents=True, exist_ok=True)
        plugin_path.write_text(_build_opencode_plugin(filtered, canonical_to_native), encoding="utf-8")
        manifest.record_file(
            plugin_rel,
            plugin_path.read_bytes(),
        )
        created.append(plugin_path)

        # Merge plugin path into opencode.json
        _merge_opencode_plugin_ref(config_path, f"./{plugin_rel}")
        rel = str(config_path.relative_to(project_root))
        if rel not in manifest.files:
            manifest.record_existing(rel)
        created.append(config_path)

    elif fmt == "copilot-json":
        # Copilot hooks JSON write (creates dedicated .github/hooks/speckit.json)
        copilot_hooks = {}
        for ev, cfg in filtered.items():
            native = canonical_to_native[ev]
            command = cfg.get("command", "")
            copilot_hooks[native] = [
                {
                    "type": "command",
                    "bash": f"python3 {EVENTS_DISPATCHER_REL} {command} {ev}",
                    "powershell": f"python3 {EVENTS_DISPATCHER_REL} {command} {ev}",
                    "timeoutSec": cfg.get("timeout", 60),
                }
            ]
        fragment = {"version": 1, "hooks": copilot_hooks}
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.write_text(json.dumps(fragment, indent=2) + "\n", encoding="utf-8")
        rel = str(config_path.relative_to(project_root))
        if rel not in manifest.files:
            manifest.record_existing(rel)
        created.append(config_path)

    elif fmt == "toml":
        # Codex config.toml custom merge
        lines: list[str] = []
        for ev, cfg in filtered.items():
            native = canonical_to_native[ev]
            timeout = cfg.get("timeout", 60)
            command = cfg.get("command", "")
            lines.append(f'[[hooks.{native}]]')
            lines.append(f'matcher = "{cfg.get("matcher", "*")}"')
            lines.append('')
            lines.append(f'[[hooks.{native}.hooks]]')
            lines.append('type = "command"')
            lines.append(f'command = \'python3 {EVENTS_DISPATCHER_REL} {command} {ev}\'')
            lines.append(f'timeout = {timeout}')
            lines.append('speckit_marker = true')
            lines.append('')
        _merge_toml_fragment(config_path, "\n".join(lines))
        rel = str(config_path.relative_to(project_root))
        if rel not in manifest.files:
            manifest.record_existing(rel)
        created.append(config_path)

    elif fmt == "json-flat":
        # Cursor hooks.json custom merge
        cursor_hooks = {}
        for ev, cfg in filtered.items():
            native = canonical_to_native[ev]
            command = cfg.get("command", "")
            cursor_hooks[native] = [
                {
                    "command": f"python3 {EVENTS_DISPATCHER_REL} {command} {ev}",
                    "type": "command",
                    "timeout": cfg.get("timeout", 60),
                    "matcher": cfg.get("matcher", "*"),
                    _SPECKIT_MARKER: True,
                }
            ]
        _merge_json_fragment(config_path, cursor_hooks)
        rel = str(config_path.relative_to(project_root))
        if rel not in manifest.files:
            manifest.record_existing(rel)
        created.append(config_path)

    elif fmt == "json-nested":
        # Claude/Qwen/Gemini/Devin/Tabnine nested config JSON merge
        nested_hooks = {}
        bridge_path_prefix = "${CLAUDE_PROJECT_DIR}/" if integration.key == "claude" else ""
        for ev, cfg in filtered.items():
            native = canonical_to_native[ev]
            command = cfg.get("command", "")
            nested_hooks[native] = [
                {
                    "matcher": cfg.get("matcher", "*"),
                    "hooks": [
                        {
                            "type": "command",
                            "command": "python3",
                            "args": [
                                bridge_path_prefix + EVENTS_DISPATCHER_REL,
                                command,
                                ev,
                            ],
                            "timeout": cfg.get("timeout", 60),
                            _SPECKIT_MARKER: True,
                        }
                    ],
                }
            ]
        _merge_json_fragment(config_path, nested_hooks)
        rel = str(config_path.relative_to(project_root))
        if rel not in manifest.files:
            manifest.record_existing(rel)
        created.append(config_path)

    return created


def remove_integration_events(integration: IntegrationBase, project_root: Path, manifest: IntegrationManifest) -> None:
    """Remove Specify-authored event entries from native config."""
    fmt = getattr(integration, "events_format", None)
    config_file = getattr(integration, "events_config_file", None)
    if config_file:
        config_path = project_root / config_file
        if config_path.exists():
            if fmt == "copilot-json":
                # Clean delete of dedicated file
                config_path.unlink(missing_ok=True)
                manifest.remove(config_file)
            elif fmt == "toml":
                _remove_toml_entries(config_path)
            elif fmt in ("json-nested", "json-flat"):
                _remove_json_entries(config_path)
            elif fmt == "ts-plugin":
                _remove_opencode_entries(config_path)

    # Clean up dispatcher script
    dispatcher_rel = EVENTS_DISPATCHER_REL
    if dispatcher_rel in manifest.files:
        dispatcher_path = project_root / dispatcher_rel
        if dispatcher_path.exists():
            dispatcher_path.unlink(missing_ok=True)
        manifest.remove(dispatcher_rel)

    # Clean up opencode TS plugin
    if integration.key == "opencode":
        plugin_rel = ".opencode/plugin/speckit-events.ts"
        if plugin_rel in manifest.files:
            plugin_path = project_root / plugin_rel
            if plugin_path.exists():
                plugin_path.unlink(missing_ok=True)
            manifest.remove(plugin_rel)


def events_stale_exclusions(integration_key: str) -> set[str]:
    """Return project-relative paths to protect from stale cleanup."""
    from .integrations import get_integration
    integration = get_integration(integration_key)
    if not integration:
        return set()
    exclusions = set()
    config_file = getattr(integration, "events_config_file", None)
    if config_file:
        exclusions.add(config_file)
    if integration_key == "opencode":
        exclusions.add(".opencode/plugin/speckit-events.ts")
    return exclusions


# -- Manifest validation ---------------------------------------------------

def validate_events(data: dict[str, Any]) -> None:
    """Validate ``events`` field in extension manifest data."""
    from .extensions import ValidationError

    events = data.get("events")
    if "events" in data and not isinstance(events, dict):
        raise ValidationError("Invalid events: expected a mapping")
    if events:
        for event_name, event_config in events.items():
            if not isinstance(event_config, dict):
                raise ValidationError(
                    f"Invalid event '{event_name}': expected a mapping"
                )
            if not event_config.get("command"):
                raise ValidationError(
                    f"Event '{event_name}' missing required 'command' field"
                )
            if event_name not in CANONICAL_EVENTS:
                raise ValidationError(
                    f"Unknown event '{event_name}': "
                    f"must be one of {sorted(CANONICAL_EVENTS)}"
                )


def has_events(data: dict[str, Any]) -> bool:
    """Return True if ``events`` is present and non-empty."""
    return bool(data.get("events"))


# -- Helper merging functions ----------------------------------------------

def _build_opencode_plugin(filtered_events: dict[str, dict[str, Any]], canonical_to_native: dict[str, str]) -> str:
    event_entries: list[str] = []
    plugin_returns: list[str] = []
    event_handlers: list[str] = []

    for ev, cfg in filtered_events.items():
        native = canonical_to_native[ev]
        command = cfg.get("command", "")
        matcher = cfg.get("matcher", "*")

        if native.startswith("tool.execute."):
            ts_hook = native
            match_cond = ""
            if matcher and matcher != "*":
                tools = [t.strip().strip('"') for t in matcher.split("|")]
                checks = " || ".join(f"input.tool === '{t.lower()}'" for t in tools)
                match_cond = f"if ({checks}) {{"
            else:
                match_cond = "{"
            event_entries.append(
                f"function _{ev}(input: any) {match_cond}\n"
                f"    runEvent('{command}', '{ev}', input);\n"
                f"  }}"
            )
            plugin_returns.append(
                f"    \"{ts_hook}\": async (input: any, output: any) => {{\n"
                f"      _{ev}(input);\n"
                f"    }},"
            )
        else:
            event_entries.append(
                f"function _{ev}(input: any) {{\n"
                f"    runEvent('{command}', '{ev}', input);\n"
                f"  }}"
            )
            event_handlers.append(
                f"      if (event.type === '{native}') {{ _{ev}(event); }}"
            )

    if event_handlers:
        plugin_returns.append(
            f"    event: async ({{ event }}) => {{\n"
            + "\n".join(event_handlers) + "\n"
            f"    }},"
        )

    return _TS_PLUGIN_TEMPLATE.format(
        event_entries="\n\n".join(event_entries),
        plugin_returns="\n".join(plugin_returns),
    )


def _merge_opencode_plugin_ref(config_path: Path, ref: str) -> None:
    existing: dict = {}
    if config_path.exists():
        try:
            existing = json.loads(config_path.read_text(encoding="utf-8"))
        except Exception:
            existing = {}
    if not isinstance(existing, dict):
        existing = {}
    plugins = existing.get("plugin", [])
    if not isinstance(plugins, list):
        plugins = []
    if ref not in plugins:
        plugins.append(ref)
    existing["plugin"] = plugins
    config_path.write_text(json.dumps(existing, indent=2) + "\n", encoding="utf-8")


def _remove_opencode_entries(config_path: Path) -> None:
    if not config_path.exists():
        return
    try:
        existing = json.loads(config_path.read_text(encoding="utf-8"))
    except Exception:
        return
    if not isinstance(existing, dict):
        return
    plugins = existing.get("plugin", [])
    if isinstance(plugins, list):
        ref = "./.opencode/plugin/speckit-events.ts"
        plugins = [p for p in plugins if p != ref]
        if plugins:
            existing["plugin"] = plugins
        else:
            existing.pop("plugin", None)
        config_path.write_text(json.dumps(existing, indent=2) + "\n", encoding="utf-8")


def _merge_toml_fragment(dst: Path, fragment: str) -> None:
    existing = ""
    if dst.exists():
        existing = dst.read_text(encoding="utf-8")
    existing = re.sub(
        r'\[\[hooks\.\w+\]\]\n(?:(?!\[\[hooks\.\w+\]\]).)*?speckit_marker = true\n*',
        "",
        existing,
        flags=re.DOTALL,
    )
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(existing.rstrip() + "\n\n" + fragment + "\n", encoding="utf-8")


def _remove_toml_entries(dst: Path) -> None:
    if not dst.exists():
        return
    existing = dst.read_text(encoding="utf-8")
    cleaned = re.sub(
        r'\[\[hooks\.\w+\]\]\n(?:(?!\[\[hooks\.\w+\]\]).)*?speckit_marker = true\n*',
        "",
        existing,
        flags=re.DOTALL,
    )
    dst.write_text(cleaned, encoding="utf-8")


def _merge_json_fragment(dst: Path, new_hooks: dict) -> None:
    existing: dict = {}
    if dst.exists():
        try:
            existing = json.loads(dst.read_text(encoding="utf-8"))
        except Exception:
            pass
    if not isinstance(existing, dict):
        existing = {}

    hooks_key = "hooks"
    existing_hooks = existing.get(hooks_key, {})
    if not isinstance(existing_hooks, dict):
        existing_hooks = {}

    for event, entries in new_hooks.items():
        existing_list = existing_hooks.get(event, [])
        if not isinstance(existing_list, list):
            existing_list = []
        # Filter out existing entries carrying our marker
        existing_list = [e for e in existing_list if not _has_marker(e)]
        existing_list.extend(entries)
        existing_hooks[event] = existing_list

    existing[hooks_key] = existing_hooks
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(json.dumps(existing, indent=2) + "\n", encoding="utf-8")


def _remove_json_entries(dst: Path) -> None:
    try:
        existing = json.loads(dst.read_text(encoding="utf-8"))
    except Exception:
        return
    if not isinstance(existing, dict):
        return
    hooks = existing.get("hooks", {})
    if not isinstance(hooks, dict):
        return
    cleaned: dict[str, list] = {}
    for event, entries in hooks.items():
        if not isinstance(entries, list):
            continue
        kept_entries = []
        for entry in entries:
            if not isinstance(entry, dict):
                kept_entries.append(entry)
                continue
            inner = entry.get("hooks")
            if isinstance(inner, list):
                kept_inner = [h for h in inner if not _has_marker(h)]
                if kept_inner:
                    entry["hooks"] = kept_inner
                    kept_entries.append(entry)
            elif _has_marker(entry):
                pass
            else:
                kept_entries.append(entry)
        if kept_entries:
            cleaned[event] = kept_entries
    if cleaned:
        existing["hooks"] = cleaned
    else:
        existing.pop("hooks", None)
    dst.write_text(json.dumps(existing, indent=2) + "\n", encoding="utf-8")


def _has_marker(entry: Any) -> bool:
    if isinstance(entry, dict):
        return entry.get(_SPECKIT_MARKER, False) is True
    return False
