"""Agent runtime events for integrations.

Provides:
- ``resolve_events`` — layered event resolution (CLI flag → YAML override → extension-declared → built-in).
- ``collect_extension_events`` — scan installed extension.yml files for ``events:``.
- ``install_integration_events`` / ``remove_integration_events`` — entry points called from ``IntegrationBase.setup()`` / ``teardown()``.
"""

from __future__ import annotations

import json
import logging
import os
import re
import shlex
import sys
import subprocess
import platform
from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml

if TYPE_CHECKING:
    from .integrations.base import IntegrationBase
    from .integrations.manifest import IntegrationManifest

logger = logging.getLogger(__name__)

# -- Constants -------------------------------------------------------------

EVENTS_DISPATCHER_DIR = Path(".specify")
EVENTS_DISPATCHER_FILENAME = "events.py"
EVENTS_DISPATCHER_REL = str(EVENTS_DISPATCHER_DIR / EVENTS_DISPATCHER_FILENAME)

YAML_OVERRIDE_FILENAME = Path(".specify") / "integration-events.yml"

_SPECKIT_MARKER = "__speckit_event__"

# Canonical event names (snake_case)
CANONICAL_EVENTS = frozenset({
    "session_start",
    "pre_tool_use",
    "post_tool_use",
    "session_end",
    "user_prompt_submit",
    "stop",
})

# -- Events Dispatcher template ---------------------------------------------

_EVENTS_DISPATCHER_TEMPLATE = '''#!/usr/bin/env python3
"""Specify CLI Event Dispatcher — dispatches agent runtime events.

Generated by: specify integration install/upgrade
Do not edit manually.
"""
import sys, subprocess, os
from pathlib import Path


def _find_specify():
    project_root = Path(__file__).parent.parent.resolve()
    # 1. Check local virtualenv
    for candidate in ("venv", ".venv"):
        py_bin = project_root / candidate / "bin" / "specify"
        if py_bin.exists():
            return [str(py_bin)]
        # Windows virtualenv
        win_bin = project_root / candidate / "Scripts" / "specify.exe"
        if win_bin.exists():
            return [str(win_bin)]

    # 2. Check python -m specify_cli
    for candidate in ("venv", ".venv"):
        py_exe = project_root / candidate / "bin" / "python"
        if py_exe.exists():
            return [str(py_exe), "-m", "specify_cli"]
        win_py = project_root / candidate / "Scripts" / "python.exe"
        if win_py.exists():
            return [str(win_py), "-m", "specify_cli"]

    # 3. Fallback to system path specify
    return ["specify"]


def main():
    if len(sys.argv) < 3:
        sys.exit(0)
    command_name = sys.argv[1]
    event_name = sys.argv[2]
    payload = sys.stdin.read() if not sys.stdin.isatty() else "{}"

    specify_args = _find_specify() + ["event", "run", command_name, event_name]
    try:
        result = subprocess.run(
            specify_args,
            input=payload,
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.stdout:
            sys.stdout.write(result.stdout)
        if result.returncode != 0:
            if result.stderr:
                sys.stderr.write(result.stderr)
            sys.exit(result.returncode)
        sys.exit(0)
    except subprocess.TimeoutExpired:
        print(f"Event {command_name} timed out", file=sys.stderr)
        sys.exit(2)
    except Exception as e:
        print(f"Event {command_name} error: {e}", file=sys.stderr)
        sys.exit(2)


if __name__ == "__main__":
    main()
'''

# -- TS plugin template (opencode) ----------------------------------------

_TS_PLUGIN_TEMPLATE = '''import {{ execSync }} from 'child_process';
import * as path from 'path';

const DISPATCHER = path.join(process.cwd(), '.specify', 'events.py');

function runEvent(command: string, event: string, input: any): void {{
  let result;
  try {{
    result = execSync(`{interpreter} ${{DISPATCHER}} ${{command}} ${{event}}`, {{
      input: JSON.stringify(input),
      stdio: ['pipe', 'inherit', 'inherit'],
      timeout: 60000,
    }});
  }} catch (e) {{
    // Propagate to OpenCode's hook machinery so only this hook is rejected,
    // not the entire host process. process.exit() would kill the agent.
    throw new Error(`specify event ${{command}} (${{event}}) failed: ${{(e as Error).message}}`);
  }}
}}

{event_entries}

export default (async ({{ client, project, directory, $ }}) => {{
  return {{
{plugin_returns}
  }};
}});
'''


# -- Command runner logic (core) --------------------------------------------

def _find_command_template(command_name: str, project_root: Path) -> tuple[Path | None, str | None]:
    # 1. Check extension .registry
    registry = project_root / ".specify" / "extensions" / ".registry"
    if registry.exists():
        try:
            data = json.loads(registry.read_text(encoding="utf-8"))
        except Exception:
            data = {}
        for ext_id, meta in data.items():
            if not isinstance(meta, dict):
                continue
            for cmd in meta.get("commands", []):
                if cmd.get("name") == command_name:
                    ext_dir = project_root / ".specify" / "extensions" / ext_id
                    return ext_dir / cmd["file"], ext_id

    # 2. Scan extension directories
    exts_dir = project_root / ".specify" / "extensions"
    if exts_dir.is_dir():
        for ext_dir in sorted(exts_dir.iterdir()):
            cmds_dir = ext_dir / "commands"
            if cmds_dir.is_dir():
                for f in cmds_dir.glob("*.md"):
                    if f.stem == command_name:
                        return f, ext_dir.name

    # 3. Check core templates in the project
    core = project_root / ".specify" / "templates" / "commands"
    if core.is_dir():
        stem = command_name.replace("speckit.", "").replace("spec.", "")
        candidate = core / f"{stem}.md"
        if candidate.exists():
            return candidate, None

    # 4. Fallback to package-bundled templates via the canonical asset
    #    resolvers (wheel: core_pack/commands; source: repo-root
    #    templates/commands). The previous bespoke inspect.getfile() math
    #    pointed at core_pack/templates/commands, which never exists in a
    #    wheel build (force-include maps templates/commands -> core_pack/commands).
    from ._assets import _locate_core_pack, _repo_root
    core_pack = _locate_core_pack()
    candidate_dirs = [
        core_pack / "commands" if core_pack is not None else None,
        _repo_root() / "templates" / "commands",
    ]
    stem = command_name.replace("speckit.", "").replace("spec.", "")
    for candidate_dir in candidate_dirs:
        if candidate_dir is None or not candidate_dir.is_dir():
            continue
        candidate = candidate_dir / f"{stem}.md"
        if candidate.exists():
            return candidate, None

    return None, None


def _resolve_event_command_argv(
    template_path: Path, project_root: Path, ext_id: str | None
) -> list[str] | None:
    """Resolve a command template's ``scripts:`` entry to a runnable argv.

    ``scripts:`` values are command strings (e.g. ``scripts/bash/setup-plan.sh --json``),
    not bare paths, so joining the whole value into a ``Path`` made ``exists()``
    false and real commands silently no-op'd. This resolves the stored variant
    (honoring the project's sh/ps/py selection), splits the command string
    safely into argv, and prepends the appropriate interpreter (Python for
    ``.py``, the platform shell otherwise). Returns ``None`` if no runnable
    script is declared.
    """
    from .integrations.base import IntegrationBase

    content = template_path.read_text(encoding="utf-8")
    m = re.match(r'^---\n(.*?)\n---', content, re.DOTALL)
    if not m:
        return None
    fm = m.group(1)
    try:
        fm_data = yaml.safe_load(fm) or {}
    except Exception:
        return None
    if not isinstance(fm_data, dict):
        return None
    scripts = fm_data.get("scripts", {})
    if not isinstance(scripts, dict):
        return None
    # Determine the requested variant from the project's persisted selection,
    # falling back to the platform default — same logic MarkdownIntegration
    # uses for command scaffolding.
    requested = _load_project_script_type(project_root)
    try:
        variant = IntegrationBase.select_script_variant(requested, scripts)
    except ValueError:
        return None
    script_cmd = scripts.get(variant)
    if not isinstance(script_cmd, str) or not script_cmd.strip():
        return None

    # Resolve the script's project-relative base so a leading path component
    # (e.g. ``scripts/bash/setup-plan.sh``) is anchored under .specify/ (core)
    # or .specify/extensions/<id>/ (extension).
    if variant == "py":
        # .py files aren't directly executable on Windows; prefix the resolved
        # interpreter. build_python_invocation returns a shell-quoted command
        # string, so split it back into argv for subprocess.
        invocation = IntegrationBase.build_python_invocation(script_cmd, project_root)
        try:
            return shlex.split(invocation, posix=(os.name != "nt"))
        except ValueError:
            return None

    # sh / ps: the command string is "<relpath> [args...]". Resolve the
    # leading path component against the project, then rejoin with the
    # remaining tokens.
    tokens = shlex.split(script_cmd, posix=(os.name != "nt"))
    if not tokens:
        return None
    script_rel = tokens[0]
    if ext_id:
        base = project_root / ".specify" / "extensions" / ext_id
    else:
        base = project_root / ".specify"
    script_abs = base / script_rel
    if not script_abs.exists():
        return None
    return [str(script_abs), *tokens[1:]]


def _load_project_script_type(project_root: Path) -> str:
    """Return the project's persisted script type ('sh'|'ps'|'py').

    Falls back to the platform default when init-options are absent or
    unreadable so event dispatch still works in a partially-initialized
    project.
    """
    default = "ps" if platform.system().lower().startswith("win") else "sh"
    try:
        from ._init_options import load_init_options
        opts = load_init_options(project_root)
        if isinstance(opts, dict):
            script = opts.get("script")
            if isinstance(script, str) and script in ("sh", "ps", "py"):
                return script
    except Exception:
        pass
    return default


def resolve_and_run_event_command(command_name: str, event_name: str, payload: str, project_root: Path) -> int:
    """Core entry point to resolve and execute an event-driven command."""
    template_path, ext_id = _find_command_template(command_name, project_root)
    if not template_path:
        logger.warning("Event command '%s' not found", command_name)
        return 0
    argv = _resolve_event_command_argv(template_path, project_root, ext_id)
    if not argv:
        logger.warning("No script found for event command '%s'", command_name)
        return 0
    try:
        result = subprocess.run(
            argv,
            input=payload,
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.stdout:
            sys.stdout.write(result.stdout)
        if result.returncode != 0:
            if result.stderr:
                sys.stderr.write(result.stderr)
            return result.returncode
        return 0
    except subprocess.TimeoutExpired:
        sys.stderr.write(f"Event command {command_name} timed out\n")
        return 2
    except Exception as e:
        sys.stderr.write(f"Event command {command_name} error: {e}\n")
        return 2


# -- Sourcing events map (CLI/Orchestration domain) -------------------------

# Resolved events map: each canonical event name maps to an *ordered list* of
# handler configs. Built-in defaults and per-extension declarations both
# contribute, so two extensions declaring ``session_start`` both run (finding
# #2) instead of the last one silently winning.
ResolvedEvents = dict[str, list[dict[str, Any]]]


def _normalize_handlers(value: Any) -> list[dict[str, Any]]:
    """Coerce a single handler config or a list of them into a validated list.

    Accepts both the legacy single-mapping shape (``{command: ...}``) and the
    explicit list shape (``[{command: ...}, ...]``). Drops any entry that is
    not a mapping or lacks a ``command`` with a warning, so a malformed user
    override never reaches installation and crashes on ``cfg.get(...)`` (#21).
    """
    if isinstance(value, dict):
        value = [value]
    if not isinstance(value, list):
        return []
    handlers: list[dict[str, Any]] = []
    for entry in value:
        if not isinstance(entry, dict):
            logger.warning("Skipping malformed event handler (expected a mapping): %r", entry)
            continue
        handlers.append(entry)
    return handlers


def _validate_resolved_event(event_name: str, handlers: list[dict[str, Any]]) -> None:
    """Validate a resolved event's handlers, raising a user-facing error.

    Raised for structural problems the user must fix (unknown event name,
    handler missing a ``command``, or ``command`` not a non-empty string per
    #17). Malformed-but-skipable entries are already dropped by
    ``_normalize_handlers``.
    """
    from .extensions import ValidationError

    if event_name not in CANONICAL_EVENTS:
        raise ValidationError(
            f"Unknown event '{event_name}': must be one of {sorted(CANONICAL_EVENTS)}"
        )
    for handler in handlers:
        command = handler.get("command")
        if not isinstance(command, str) or not command.strip():
            raise ValidationError(
                f"Event '{event_name}' handler missing required non-empty 'command' string"
            )


def resolve_events(
    integration_key: str,
    integration_config: dict[str, Any] | None,
    project_root: Path,
    parsed_options: dict[str, Any] | None,
) -> ResolvedEvents:
    """Resolve the final event set for an integration.

    Returns a mapping of canonical event name → ordered list of handler
    configs. Layers (lowest → highest precedence):

    1. CLI gate ``--events false`` → empty map (caller still removes prior
       native hooks; see ``install_integration_events``).
    2. Built-in defaults from ``integration_config["events"]`` (single-config
       per event, wrapped as one-element lists).
    3. Extension-declared ``events:`` — appended per extension so multiple
       extensions can declare the same event (#2).
    4. User YAML override (``.specify/integration-events.yml``) — replaces the
       accumulated set entirely when the integration key is present. Validated
       (#21) before returning; a malformed override is warned about and
       ignored rather than crashing downstream.
    """
    # Layer 1: CLI flag gate
    if parsed_options:
        events_flag = str(parsed_options.get("events", "true")).lower()
        if events_flag in ("false", "0", "no", "off"):
            return {}

    events: ResolvedEvents = {}

    # Layer 2: built-in defaults from integration config
    if integration_config and isinstance(integration_config.get("events"), dict):
        for ev, cfg in integration_config["events"].items():
            handlers = _normalize_handlers(cfg)
            if handlers:
                events.setdefault(ev, []).extend(handlers)

    # Layer 3: extension-declared events (accumulated, not overwriting)
    for ev, handlers in collect_extension_events(project_root).items():
        events.setdefault(ev, []).extend(handlers)

    # Layer 4: user YAML override (replaces entirely if key present)
    override_file = project_root / YAML_OVERRIDE_FILENAME
    if override_file.exists():
        try:
            override = yaml.safe_load(override_file.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError:
            logger.warning("Could not parse %s; ignoring override", override_file)
            override = {}
        integrations = override.get("integrations", {}) if isinstance(override, dict) else {}
        if isinstance(integrations, dict) and integration_key in integrations:
            key_data = integrations[integration_key]
            key_events = key_data.get("events", {}) if isinstance(key_data, dict) else {}
            if not isinstance(key_events, dict):
                logger.warning(
                    "Override %s: 'events' for '%s' is not a mapping; ignoring override",
                    override_file, integration_key,
                )
            else:
                resolved_override: ResolvedEvents = {}
                for ev, raw in key_events.items():
                    handlers = _normalize_handlers(raw)
                    if not handlers:
                        logger.warning(
                            "Override %s: event '%s' has no valid handler; skipping entry",
                            override_file, ev,
                        )
                        continue
                    try:
                        _validate_resolved_event(ev, handlers)
                    except Exception as exc:
                        logger.warning(
                            "Override %s: invalid event '%s': %s; ignoring override",
                            override_file, ev, exc,
                        )
                        resolved_override = {}
                        break
                    resolved_override[ev] = handlers
                events = resolved_override

    return events


def collect_extension_events(project_root: Path) -> ResolvedEvents:
    """Scan all installed extensions for ``events:`` declarations.

    Returns a mapping of event name → list of handler configs. Multiple
    extensions declaring the same event each contribute a handler (in
    extension-directory sort order), so callers can emit all of them (#2).

    Honors the extension registry's ``enabled`` flag (#1): an explicitly
    disabled extension's events are skipped so disabling an extension actually
    deactivates its runtime hooks. Extensions absent from the registry (e.g.
    a partially-staged install) are still included to preserve the on-disk
    scan behavior.
    """
    from .extensions import ExtensionRegistry

    events: ResolvedEvents = {}
    exts_dir = project_root / ".specify" / "extensions"
    if not exts_dir.is_dir():
        return events

    # Build the set of explicitly-disabled extension IDs. Extensions not
    # tracked in the registry are treated as enabled (backward compat).
    disabled_ids: set[str] = set()
    try:
        registry = ExtensionRegistry(exts_dir)
        for ext_id, meta in registry.list_by_priority(include_disabled=True):
            if not isinstance(meta, dict) or not meta.get("enabled", True):
                disabled_ids.add(ext_id)
    except Exception:
        pass

    for ext_dir in sorted(exts_dir.iterdir()):
        if not ext_dir.is_dir():
            continue
        if ext_dir.name in disabled_ids:
            continue
        ext_yml = ext_dir / "extension.yml"
        if not ext_yml.exists():
            continue
        try:
            data = yaml.safe_load(ext_yml.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError:
            continue
        if not isinstance(data, dict):
            continue
        runtime = data.get("events", {}) or {}
        if not isinstance(runtime, dict):
            continue
        for event, config in runtime.items():
            handlers = _normalize_handlers(config)
            if handlers:
                events.setdefault(event, []).extend(handlers)
    return events


# -- Writing/Merging Config (Integration domain) ---------------------------

def _resolve_interpreter(project_root: Path) -> str:
    """Resolve a portable Python interpreter for native hook commands (#16).

    Delegates to ``IntegrationBase.resolve_python_interpreter`` so generated
    commands honor the project venv and never hard-code ``python3`` (which is
    commonly absent on Windows even when ``py.exe``/``python.exe`` exist).
    """
    from .integrations.base import IntegrationBase
    return IntegrationBase.resolve_python_interpreter(project_root)


def _native_timeout(integration: IntegrationBase, timeout_seconds: Any) -> int:
    """Return the timeout in the unit the integration's native config expects.

    Claude/Cursor/Codex/Copilot measure timeouts in seconds; Gemini measures
    in milliseconds (#7). An integration declares its unit via
    ``events_timeout_unit`` (``"s"`` default, ``"ms"`` for Gemini).
    """
    try:
        seconds = int(timeout_seconds)
    except (TypeError, ValueError):
        seconds = 60
    if getattr(integration, "events_timeout_unit", "s") == "ms":
        return seconds * 1000
    return seconds


def _dispatcher_command(
    integration: IntegrationBase,
    project_root: Path,
    command_name: str,
    event_name: str,
) -> str:
    """Build the single shell command string that invokes the dispatcher (#6).

    Claude/Gemini/Qwen/Devin/Tabnine accept one ``command`` string (not a
    ``command``+``args`` split), so each adapter renders a complete invocation:
    ``<interpreter> <dispatcher> <command> <event>``. The interpreter is
    resolved portably (#16); Claude's dispatcher path is prefixed with
    ``${CLAUDE_PROJECT_DIR}/`` (Claude expands it before shell execution).
    """
    interpreter = _resolve_interpreter(project_root)
    if integration.key == "claude":
        dispatcher = "${CLAUDE_PROJECT_DIR}/" + EVENTS_DISPATCHER_REL
    else:
        dispatcher = EVENTS_DISPATCHER_REL
    return f"{interpreter} {dispatcher} {command_name} {event_name}"


def install_integration_events(
    integration: IntegrationBase,
    project_root: Path,
    manifest: IntegrationManifest,
    events: ResolvedEvents,
) -> list[Path]:
    """Generate dispatcher, merge native config, return created files.

    ``events`` maps each canonical event to an ordered list of handler configs
    (#2); every handler is emitted as a separate native hook entry so two
    extensions declaring ``session_start`` both run.
    """
    canonical_to_native = getattr(integration, "CANONICAL_TO_NATIVE", {})
    if not canonical_to_native:
        return []

    # Filter to only supported events, preserving all handlers per event.
    filtered: ResolvedEvents = {}
    for ev, handlers in events.items():
        if not isinstance(handlers, list):
            continue
        if ev in canonical_to_native:
            filtered[ev] = handlers
        else:
            print(
                f"\u26a0\ufe0f  {integration.key} does not support '{ev}' events; skipping",
                file=sys.stderr,
            )

    # #3: an empty resolved map (--events false, or override disabling events)
    # must still strip prior Specify hooks from this integration's native
    # config rather than leaving them active. The shared dispatcher is left
    # untouched — another integration may still reference it (#10).
    if not filtered:
        _remove_native_event_hooks(integration, project_root, manifest)
        return []

    created: list[Path] = []

    # 1. Generate events.py dispatcher script (#12: validate destination first)
    dispatcher_dir = project_root / EVENTS_DISPATCHER_DIR
    dispatcher_path = dispatcher_dir / EVENTS_DISPATCHER_FILENAME
    _ensure_safe_destination(dispatcher_path)
    dispatcher_dir.mkdir(parents=True, exist_ok=True)
    dispatcher_path.write_text(_EVENTS_DISPATCHER_TEMPLATE, encoding="utf-8")
    dispatcher_path.chmod(0o755)
    manifest.record_file(
        str(dispatcher_path.relative_to(project_root)),
        dispatcher_path.read_bytes(),
    )
    created.append(dispatcher_path)

    # 2. Format-specific merge/write
    fmt = getattr(integration, "events_format", "json-nested")
    config_file = getattr(integration, "events_config_file", None)
    if not config_file:
        return created

    config_path = project_root / config_file

    if fmt == "ts-plugin":
        # Opencode TS plugin custom merge
        plugin_rel = ".opencode/plugin/speckit-events.ts"
        plugin_path = project_root / plugin_rel
        _ensure_safe_destination(plugin_path)
        plugin_path.parent.mkdir(parents=True, exist_ok=True)
        plugin_path.write_text(
            _build_opencode_plugin(filtered, canonical_to_native, _resolve_interpreter(project_root)),
            encoding="utf-8",
        )
        manifest.record_file(
            plugin_rel,
            plugin_path.read_bytes(),
        )
        created.append(plugin_path)

        # Merge plugin path into opencode.json
        _merge_opencode_plugin_ref(config_path, f"./{plugin_rel}")
        rel = str(config_path.relative_to(project_root))
        if rel not in manifest.files:
            manifest.record_existing(rel)
        created.append(config_path)

    elif fmt == "copilot-json":
        # Copilot dedicated .github/hooks/speckit.json. Each handler becomes
        # its own entry in the native event's list (#2), with bash/powershell
        # variants sharing one resolved interpreter (#16). Entries carry the
        # ownership marker so a pre-existing user-authored file is merged
        # (owned entries replaced) rather than overwritten (#8), and teardown
        # removes only owned entries.
        copilot_hooks: dict[str, list[dict[str, Any]]] = {}
        for ev, handlers in filtered.items():
            native = canonical_to_native[ev]
            entries: list[dict[str, Any]] = []
            for cfg in handlers:
                command = cfg.get("command", "")
                dispatcher_cmd = _dispatcher_command(integration, project_root, command, ev)
                entries.append(
                    {
                        "type": "command",
                        "bash": dispatcher_cmd,
                        "powershell": dispatcher_cmd,
                        "timeoutSec": _native_timeout(integration, cfg.get("timeout", 60)),
                        _SPECKIT_MARKER: True,
                    }
                )
            copilot_hooks[native] = entries
        _merge_copilot_json(config_path, copilot_hooks)
        rel = str(config_path.relative_to(project_root))
        if rel not in manifest.files:
            manifest.record_existing(rel)
        created.append(config_path)

    elif fmt == "toml":
        # Codex config.toml custom merge. One [[hooks.<native>.hooks]] block
        # per handler so multiple handlers per event all emit (#2).
        lines: list[str] = []
        for ev, handlers in filtered.items():
            native = canonical_to_native[ev]
            for cfg in handlers:
                command = cfg.get("command", "")
                dispatcher_cmd = _dispatcher_command(integration, project_root, command, ev)
                lines.append(f'[[hooks.{native}]]')
                lines.append(f'matcher = "{cfg.get("matcher", "*")}"')
                lines.append('')
                lines.append(f'[[hooks.{native}.hooks]]')
                lines.append('type = "command"')
                lines.append(f'command = {_toml_quote(dispatcher_cmd)}')
                lines.append(f'timeout = {_native_timeout(integration, cfg.get("timeout", 60))}')
                lines.append('speckit_marker = true')
                lines.append('')
        _merge_toml_fragment(config_path, "\n".join(lines))
        rel = str(config_path.relative_to(project_root))
        if rel not in manifest.files:
            manifest.record_existing(rel)
        created.append(config_path)

    elif fmt == "json-flat":
        # Cursor hooks.json custom merge. Flat command-string entries, one
        # per handler (#2), single resolved command string (#6/#16).
        cursor_hooks: dict[str, list[dict[str, Any]]] = {}
        for ev, handlers in filtered.items():
            native = canonical_to_native[ev]
            entries: list[dict[str, Any]] = []
            for cfg in handlers:
                command = cfg.get("command", "")
                dispatcher_cmd = _dispatcher_command(integration, project_root, command, ev)
                entries.append(
                    {
                        "command": dispatcher_cmd,
                        "type": "command",
                        "timeout": _native_timeout(integration, cfg.get("timeout", 60)),
                        "matcher": cfg.get("matcher", "*"),
                        _SPECKIT_MARKER: True,
                    }
                )
            cursor_hooks[native] = entries
        _merge_json_fragment(config_path, cursor_hooks)
        rel = str(config_path.relative_to(project_root))
        if rel not in manifest.files:
            manifest.record_existing(rel)
        created.append(config_path)

    elif fmt == "json-nested":
        # Claude/Qwen/Gemini/Devin/Tabnine nested config JSON merge.
        # Native schema is a single ``command`` string per hook (not
        # command+args), so each handler renders one complete dispatcher
        # invocation (#6). Gemini timeouts are converted to ms (#7).
        nested_hooks: dict[str, list[dict[str, Any]]] = {}
        for ev, handlers in filtered.items():
            native = canonical_to_native[ev]
            matcher = handlers[0].get("matcher", "*") if handlers else "*"
            inner_hooks: list[dict[str, Any]] = []
            for cfg in handlers:
                command = cfg.get("command", "")
                dispatcher_cmd = _dispatcher_command(integration, project_root, command, ev)
                inner_hooks.append(
                    {
                        "type": "command",
                        "command": dispatcher_cmd,
                        "timeout": _native_timeout(integration, cfg.get("timeout", 60)),
                        _SPECKIT_MARKER: True,
                    }
                )
            nested_hooks[native] = [
                {
                    "matcher": matcher,
                    "hooks": inner_hooks,
                }
            ]
        _merge_json_fragment(config_path, nested_hooks)
        rel = str(config_path.relative_to(project_root))
        if rel not in manifest.files:
            manifest.record_existing(rel)
        created.append(config_path)

    return created


def _remove_native_event_hooks(
    integration: IntegrationBase,
    project_root: Path,
    manifest: IntegrationManifest,
) -> None:
    """Remove Specify-authored hooks from *this* integration's native config.

    Used both by full teardown and by the empty-resolved-map install path (#3).
    Does NOT touch the shared dispatcher (another integration may still
    reference it — #10).
    """
    fmt = getattr(integration, "events_format", None)
    config_file = getattr(integration, "events_config_file", None)
    if not config_file:
        return
    config_path = project_root / config_file
    if not config_path.exists():
        return
    deleted = False
    if fmt == "copilot-json":
        deleted = _remove_copilot_entries(config_path)
    elif fmt == "toml":
        deleted = _remove_toml_entries(config_path)
    elif fmt in ("json-nested", "json-flat"):
        deleted = _remove_json_entries(config_path)
    elif fmt == "ts-plugin":
        deleted = _remove_opencode_entries(config_path)
    if deleted:
        manifest.remove(config_file)


def _other_event_integrations_reference_dispatcher(
    project_root: Path, excluding_key: str
) -> bool:
    """Return True if another installed event-capable integration still
    references the shared ``.specify/events.py`` dispatcher (#10).

    Inspects each installed integration's manifest (excluding *excluding_key*)
    for the dispatcher path so uninstalling one multi-install event-capable
    integration doesn't delete the dispatcher the others still rely on.
    """
    from .integrations._helpers import _read_integration_json
    from .integrations.manifest import IntegrationManifest
    from .integration_state import installed_integration_keys

    state = _read_integration_json(project_root)
    for key in installed_integration_keys(state):
        if key == excluding_key:
            continue
        try:
            manifest = IntegrationManifest.load(key, project_root)
        except Exception:
            continue
        if EVENTS_DISPATCHER_REL in manifest.files:
            return True
    return False


def remove_integration_events(
    integration: IntegrationBase, project_root: Path, manifest: IntegrationManifest
) -> None:
    """Remove Specify-authored event entries from native config.

    The shared ``.specify/events.py`` dispatcher is deleted only when no other
    installed event-capable integration still references it (#10); otherwise
    it is left in place so multi-install setups don't lose the dispatcher
    mid-stream.
    """
    _remove_native_event_hooks(integration, project_root, manifest)

    # Clean up dispatcher script only if no other integration still uses it.
    dispatcher_rel = EVENTS_DISPATCHER_REL
    if dispatcher_rel in manifest.files:
        if not _other_event_integrations_reference_dispatcher(project_root, integration.key):
            dispatcher_path = project_root / dispatcher_rel
            if dispatcher_path.exists():
                dispatcher_path.unlink(missing_ok=True)
            manifest.remove(dispatcher_rel)

    # Clean up opencode TS plugin (owned solely by the opencode integration).
    if integration.key == "opencode":
        plugin_rel = ".opencode/plugin/speckit-events.ts"
        if plugin_rel in manifest.files:
            plugin_path = project_root / plugin_rel
            if plugin_path.exists():
                plugin_path.unlink(missing_ok=True)
            manifest.remove(plugin_rel)


def events_stale_exclusions(integration_key: str) -> set[str]:
    """Return project-relative paths to protect from stale cleanup."""
    from .integrations import get_integration
    integration = get_integration(integration_key)
    if not integration:
        return set()
    exclusions = set()
    config_file = getattr(integration, "events_config_file", None)
    if config_file:
        exclusions.add(config_file)
    if integration_key == "opencode":
        exclusions.add(".opencode/plugin/speckit-events.ts")
    return exclusions


def refresh_integration_events(project_root: Path) -> None:
    """Re-resolve and re-emit native event config for every installed
    event-capable integration (#1).

    Called after extension state changes (install/uninstall/enable/disable)
    so that extension-declared events are regenerated in each installed
    integration's native config — otherwise the documented install-after-
    ``specify init`` flow is inert and disabled/removed extension events stay
    active. Each integration is refreshed independently; a failure for one
    logs a warning without aborting the others.
    """
    from .integrations import get_integration
    from .integrations._helpers import _read_integration_json
    from .integrations.manifest import IntegrationManifest
    from .integration_state import installed_integration_keys

    state = _read_integration_json(project_root)
    for key in installed_integration_keys(state):
        integration = get_integration(key)
        if integration is None or not integration.supports_events():
            continue
        try:
            manifest = IntegrationManifest.load(key, project_root)
        except Exception as exc:
            logger.warning("Could not load manifest for '%s'; skipping event refresh: %s", key, exc)
            continue
        try:
            # Strip prior Specify hooks, then re-emit from the freshly
            # resolved set (which now honors the registry's enabled flag).
            _remove_native_event_hooks(integration, project_root, manifest)
            events_map = resolve_events(key, integration.config, project_root, None)
            if events_map:
                install_integration_events(integration, project_root, manifest, events_map)
            manifest.save()
        except Exception as exc:
            logger.warning("Failed to refresh events for '%s': %s", key, exc)


# -- Manifest validation ---------------------------------------------------

def validate_events(data: dict[str, Any]) -> None:
    """Validate ``events`` field in extension manifest data."""
    from .extensions import ValidationError

    events = data.get("events")
    if "events" in data and not isinstance(events, dict):
        raise ValidationError("Invalid events: expected a mapping")
    if events:
        for event_name, event_config in events.items():
            if not isinstance(event_config, dict):
                raise ValidationError(
                    f"Invalid event '{event_name}': expected a mapping"
                )
            command = event_config.get("command")
            # #17: command must be a non-empty string. A truthy non-string
            # (e.g. command: [foo]) would pass a bare truthiness check and
            # later render into invalid native configuration.
            if not isinstance(command, str) or not command.strip():
                raise ValidationError(
                    f"Event '{event_name}' missing required 'command' string"
                )
            if event_name not in CANONICAL_EVENTS:
                raise ValidationError(
                    f"Unknown event '{event_name}': "
                    f"must be one of {sorted(CANONICAL_EVENTS)}"
                )


def has_events(data: dict[str, Any]) -> bool:
    """Return True if ``events`` is present and non-empty."""
    return bool(data.get("events"))


# -- Helper merging functions ----------------------------------------------

def _toml_quote(value: str) -> str:
    """Render *value* as a TOML basic string via the shared escaper."""
    from ._toml_string import escape_toml_basic
    return escape_toml_basic(value)


def _build_opencode_plugin(
    filtered_events: ResolvedEvents,
    canonical_to_native: dict[str, str],
    interpreter: str,
) -> str:
    """Render the opencode TS plugin for the resolved event set.

    Each canonical event may carry multiple handlers (#2); all handlers for a
    native event are invoked from one generated function. The dispatcher is
    launched with the resolved Python interpreter (#16) instead of a
    hard-coded ``python3``.
    """
    event_entries: list[str] = []
    plugin_returns: list[str] = []
    event_handlers: list[str] = []

    for ev, handlers in filtered_events.items():
        native = canonical_to_native[ev]

        # Build the body: one runEvent() call per handler, with an optional
        # tool-name matcher guard for tool.execute.* hooks.
        body_lines: list[str] = []
        for cfg in handlers:
            command = str(cfg.get("command", ""))
            matcher = cfg.get("matcher", "*")
            if native.startswith("tool.execute."):
                if matcher and matcher != "*":
                    tools = [t.strip().strip('"') for t in matcher.split("|")]
                    checks = " || ".join(f"input.tool === '{t.lower()}'" for t in tools)
                    body_lines.append(
                        f"    if ({checks}) {{ runEvent('{command}', '{ev}', input); }}"
                    )
                else:
                    body_lines.append(f"    runEvent('{command}', '{ev}', input);")
            else:
                body_lines.append(f"    runEvent('{command}', '{ev}', input);")

        if native.startswith("tool.execute."):
            ts_hook = native
            event_entries.append(
                f"function _{ev}(input: any) {{\n"
                + "\n".join(body_lines) + "\n"
                "  }"
            )
            plugin_returns.append(
                f"    \"{ts_hook}\": async (input: any, output: any) => {{\n"
                f"      _{ev}(input);\n"
                f"    }},"
            )
        else:
            event_entries.append(
                f"function _{ev}(input: any) {{\n"
                + "\n".join(body_lines) + "\n"
                "  }"
            )
            event_handlers.append(
                f"      if (event.type === '{native}') {{ _{ev}(event); }}"
            )

    if event_handlers:
        plugin_returns.append(
            "    event: async ({ event }) => {\n"
            + "\n".join(event_handlers) + "\n"
            "    },"
        )

    return _TS_PLUGIN_TEMPLATE.format(
        interpreter=interpreter,
        event_entries="\n\n".join(event_entries),
        plugin_returns="\n".join(plugin_returns),
    )


def _merge_opencode_plugin_ref(config_path: Path, ref: str) -> None:
    """Merge the speckit-events plugin ref into opencode.json.

    Aborts with a warning (#23) when the file cannot be parsed (e.g. JSONC or
    malformed JSON) instead of resetting user configuration to ``{}``.
    """
    existing = _load_user_json(config_path)
    if existing is None:
        return
    plugins = existing.get("plugin", [])
    if not isinstance(plugins, list):
        plugins = []
    if ref not in plugins:
        plugins.append(ref)
    existing["plugin"] = plugins
    _safe_write_json(config_path, existing)


def _remove_opencode_entries(config_path: Path) -> bool:
    """Remove the speckit-events plugin ref from opencode.json (#23).

    Returns True if the file was deleted (now empty of user content), False
    otherwise. Aborts without writing when the file cannot be parsed.
    """
    existing = _load_user_json(config_path)
    if existing is None:
        return False
    plugins = existing.get("plugin", [])
    if isinstance(plugins, list):
        ref = "./.opencode/plugin/speckit-events.ts"
        plugins = [p for p in plugins if p != ref]
        if plugins:
            existing["plugin"] = plugins
        else:
            existing.pop("plugin", None)
    if not existing:
        config_path.unlink(missing_ok=True)
        return True
    _safe_write_json(config_path, existing)
    return False


def _merge_toml_fragment(dst: Path, fragment: str) -> None:
    _ensure_safe_destination(dst)
    existing = ""
    if dst.exists():
        existing = dst.read_text(encoding="utf-8")
    existing = re.sub(
        r'\[\[hooks\.\w+\]\]\n(?:(?!\[\[hooks\.\w+\]\]).)*?speckit_marker = true\n*',
        "",
        existing,
        flags=re.DOTALL,
    )
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(existing.rstrip() + "\n\n" + fragment + "\n", encoding="utf-8")


def _remove_toml_entries(dst: Path) -> bool:
    """Remove Specify-marked TOML entries; delete the file if now empty (#14).

    Returns True if the file was deleted (no user content remained).
    """
    if not dst.exists():
        return False
    existing = dst.read_text(encoding="utf-8")
    cleaned = re.sub(
        r'\[\[hooks\.\w+\]\]\n(?:(?!\[\[hooks\.\w+\]\]).)*?speckit_marker = true\n*',
        "",
        existing,
        flags=re.DOTALL,
    )
    # If only whitespace/comments remain, the file had no user content —
    # delete it rather than leaving an empty stub that confuses uninstall.
    stripped = "\n".join(
        line for line in cleaned.splitlines()
        if line.strip() and not line.strip().startswith("#")
    )
    if not stripped:
        dst.unlink(missing_ok=True)
        return True
    dst.write_text(cleaned, encoding="utf-8")
    return False


def _merge_copilot_json(dst: Path, new_hooks: dict[str, list]) -> None:
    """Merge Specify-owned hooks into Copilot's dedicated hooks JSON (#8).

    A pre-existing user-authored ``.github/hooks/speckit.json`` is merged
    (owned entries replaced via markers) rather than overwritten, and a
    parse failure aborts instead of resetting user content (#22).
    """
    existing = _load_user_json(dst)
    if existing is None:
        return
    if not isinstance(existing, dict):
        existing = {}
    existing.setdefault("version", 1)
    existing_hooks = existing.get("hooks", {})
    if not isinstance(existing_hooks, dict):
        existing_hooks = {}
    # #11: strip ALL Specify-marked entries from every event first.
    cleaned_hooks: dict[str, list] = {}
    for event, entries in existing_hooks.items():
        if not isinstance(entries, list):
            continue
        kept_entries = _drop_marked_entries(entries)
        if kept_entries:
            cleaned_hooks[event] = kept_entries
    for event, entries in new_hooks.items():
        cleaned_hooks.setdefault(event, []).extend(entries)
    if cleaned_hooks:
        existing["hooks"] = cleaned_hooks
    else:
        existing.pop("hooks", None)
    _safe_write_json(dst, existing)


def _remove_copilot_entries(dst: Path) -> bool:
    """Remove Specify-owned hooks from Copilot's hooks JSON (#8, #14).

    Deletes the file when no user-authored hooks remain; otherwise keeps the
    file with user content. Aborts (no write) on parse failure (#22).
    """
    existing = _load_user_json(dst)
    if existing is None:
        return False
    if not isinstance(existing, dict):
        return False
    hooks = existing.get("hooks", {})
    if not isinstance(hooks, dict):
        hooks = {}
    cleaned: dict[str, list] = {}
    for event, entries in hooks.items():
        if not isinstance(entries, list):
            continue
        kept_entries = _drop_marked_entries(entries)
        if kept_entries:
            cleaned[event] = kept_entries
    if cleaned:
        existing["hooks"] = cleaned
    else:
        existing.pop("hooks", None)
    # Dedicated Spec-Kit file: delete when only the (Spec-Kit-invented)
    # ``version`` key would remain — no user content to preserve.
    user_keys = {k for k in existing if k != "version"}
    if not user_keys:
        dst.unlink(missing_ok=True)
        return True
    _safe_write_json(dst, existing)
    return False


def _merge_json_fragment(dst: Path, new_hooks: dict) -> None:
    """Merge Specify-authored hook entries into a native JSON config.

    Idempotent: removes ALL prior Specify-marked entries from every event in
    the existing config first (#11), so an override that drops an event (e.g.
    ``pre_tool_use`` → ``stop``) doesn't leave stale marked entries behind.
    Marker detection recurses into nested ``hooks`` arrays (#9) so a
    matcher-group containing Specify-owned inner hooks is recognized and
    replaced rather than duplicated on every upgrade.

    Aborts with a warning (no write) when the existing file cannot be parsed
    (#22) — e.g. JSONC with comments — instead of resetting user content to
    ``{}``.
    """
    existing = _load_user_json(dst)
    if existing is None:
        return
    if not isinstance(existing, dict):
        existing = {}

    hooks_key = "hooks"
    existing_hooks = existing.get(hooks_key, {})
    if not isinstance(existing_hooks, dict):
        existing_hooks = {}

    # #11: strip ALL Specify-marked entries from every event first.
    cleaned_hooks: dict[str, list] = {}
    for event, entries in existing_hooks.items():
        if not isinstance(entries, list):
            continue
        kept_entries = _drop_marked_entries(entries)
        if kept_entries:
            cleaned_hooks[event] = kept_entries

    # Then add the newly resolved set.
    for event, entries in new_hooks.items():
        cleaned_hooks.setdefault(event, []).extend(entries)

    if cleaned_hooks:
        existing[hooks_key] = cleaned_hooks
    else:
        existing.pop(hooks_key, None)
    _safe_write_json(dst, existing)


def _drop_marked_entries(entries: list) -> list:
    """Return *entries* with Specify-marked hooks removed, preserving user hooks.

    Handles both flat entries (marker on the entry itself) and nested entries
    (marker on inner ``hooks`` elements). A nested matcher-group whose inner
    hooks are all Specify-owned is dropped; one with surviving user inner
    hooks is kept with only the user hooks retained (#9).
    """
    kept: list = []
    for entry in entries:
        if not isinstance(entry, dict):
            kept.append(entry)
            continue
        inner = entry.get("hooks")
        if isinstance(inner, list):
            kept_inner = [h for h in inner if not _has_marker(h)]
            if kept_inner:
                entry["hooks"] = kept_inner
                kept.append(entry)
            # else: outer group was entirely Specify-owned → drop
        elif _has_marker(entry):
            pass  # flat Specify-owned entry → drop
        else:
            kept.append(entry)
    return kept


def _load_user_json(path: Path) -> dict | None:
    """Load a user-owned JSON file, aborting (None) on parse failure (#22/#23).

    Returns the parsed dict, or ``None`` when the file is missing or cannot be
    parsed (e.g. JSONC with comments, or temporarily malformed JSON). Callers
    must skip the merge rather than resetting user content to ``{}``.
    """
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, ValueError) as exc:
        logger.warning(
            "Could not parse %s (may contain JSONC comments or be malformed); "
            "skipping event-config merge to preserve user content.",
            path,
        )
        logger.debug("Parse error detail: %s", exc)
        return None
    if not isinstance(data, dict):
        logger.warning("%s is not a JSON object; skipping event-config merge.", path)
        return None
    return data


def _safe_write_json(dst: Path, data: dict) -> None:
    """Write *data* as JSON to *dst* after validating the destination (#12)."""
    _ensure_safe_destination(dst)
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def _ensure_safe_destination(dst: Path) -> None:
    """Validate a write target is a regular path inside the project (#12).

    Walks each path component and rejects symlinks (which could escape the
    project — e.g. a symlinked ``.claude`` or ``.specify`` directory pointing
    outside the repo would redirect writes to external files). Then validates
    lexical containment so ``..`` traversal is also rejected.
    """
    from .agents import CommandRegistrar

    # Walk each component so a symlinked ancestor (e.g. ``.claude`` → outside)
    # cannot be silently followed. Mirrors IntegrationManifest.record_existing.
    walked = dst.anchor and Path(dst.anchor) or Path("/")
    for part in dst.relative_to(dst.anchor).parts if dst.anchor else dst.parts:
        walked = walked / part
        if walked.is_symlink():
            raise ValueError(
                f"Refusing to write event config through a symlink: {walked}"
            )

    # Containment check against the nearest existing ancestor directory.
    base = dst.parent
    while not base.exists() and base != base.parent:
        base = base.parent
    CommandRegistrar._ensure_inside(dst, base)


def _remove_json_entries(dst: Path) -> bool:
    """Remove Specify-authored entries; delete the file if now empty (#14).

    Returns True if the file was deleted (Spec Kit created it and no user
    content remains), False otherwise.
    """
    existing = _load_user_json(dst)
    if existing is None:
        return False
    hooks = existing.get("hooks", {})
    if not isinstance(hooks, dict):
        return False
    cleaned: dict[str, list] = {}
    for event, entries in hooks.items():
        if not isinstance(entries, list):
            continue
        kept_entries = _drop_marked_entries(entries)
        if kept_entries:
            cleaned[event] = kept_entries
    if cleaned:
        existing["hooks"] = cleaned
    else:
        existing.pop("hooks", None)
    # #14: if the config is now empty (no user content), delete the file
    # rather than leaving a ``{}`` that confuses manifest.uninstall().
    if not existing:
        dst.unlink(missing_ok=True)
        return True
    _safe_write_json(dst, existing)
    return False


def _has_marker(entry: Any) -> bool:
    """Return True if *entry* (or any nested inner hook) is Specify-marked (#9).

    Flat entries carry the marker directly; nested matcher-groups carry it on
    their inner ``hooks`` elements, so detection recurses one level to
    recognize groups that are (wholly or partly) Specify-owned.
    """
    if not isinstance(entry, dict):
        return False
    if entry.get(_SPECKIT_MARKER, False) is True:
        return True
    inner = entry.get("hooks")
    if isinstance(inner, list):
        return any(_has_marker(h) for h in inner)
    return False
