"""Agent runtime hooks for integrations.

Provides:
- ``resolve_hooks`` — layered hook resolution (CLI flag → YAML override → extension-declared → built-in).
- ``collect_extension_runtime_hooks`` — scan installed extension.yml files for ``runtime_hooks:``.
- ``HookAdapter`` / adapters — generate and merge native hook config per agent CLI.
- ``install_integration_hooks`` / ``remove_integration_hooks`` — entry points called from ``IntegrationBase.setup()`` / ``teardown()``.

"""

from __future__ import annotations

import json
import logging
import re
from abc import ABC, abstractmethod
from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml

if TYPE_CHECKING:
    from .base import IntegrationBase
    from .manifest import IntegrationManifest

logger = logging.getLogger(__name__)

# -- Constants -------------------------------------------------------------

HOOK_BRIDGE_DIR = Path(".specify") / "hooks"
HOOK_BRIDGE_FILENAME = "bridge.py"
HOOK_BRIDGE_REL = str(HOOK_BRIDGE_DIR / HOOK_BRIDGE_FILENAME)

YAML_OVERRIDE_FILENAME = Path(".specify") / "integration-hooks.yml"

# Sentinel marker embedded in generated native config entries so we can
# identify and remove only our entries on uninstall/upgrade.
_SPECKIT_MARKER = "__speckit_hook__"

# Canonical runtime hook event names that extensions use in ``runtime_hooks:``.
# Adapters translate these to each agent's native event names via
# ``CANONICAL_TO_NATIVE``.  Extensions never need to know agent-specific names.
CANONICAL_RUNTIME_EVENTS = frozenset({
    "PreToolUse",
    "PostToolUse",
    "Stop",
    "SessionStart",
    "SessionEnd",
    "UserPromptSubmit",
})

# -- Bridge script template ------------------------------------------------

_BRIDGE_TEMPLATE = '''#!/usr/bin/env python3
"""Specify CLI Hook Bridge — dispatches agent runtime hooks to slash commands.

Generated by: specify integration install/upgrade
Do not edit manually. Regenerate with: specify integration upgrade
"""
import json, sys, subprocess, re, os, platform
from pathlib import Path


def _project_root():
    for env_var in ("CLAUDE_PROJECT_DIR", "CURSOR_PROJECT_ROOT", "PROJECT_ROOT"):
        val = os.environ.get(env_var)
        if val and Path(val).is_dir():
            return Path(val)
    return Path.cwd()


def _find_command_template(command_name, project_root):
    # 1. Check extension .registry
    registry = project_root / ".specify" / "extensions" / ".registry"
    if registry.exists():
        try:
            data = json.loads(registry.read_text(encoding="utf-8"))
        except Exception:
            data = {}
        for ext_id, meta in data.items():
            if not isinstance(meta, dict):
                continue
            for cmd in meta.get("commands", []):
                if cmd.get("name") == command_name:
                    ext_dir = project_root / ".specify" / "extensions" / ext_id
                    return ext_dir / cmd["file"], ext_id
    # 2. Scan extension directories
    exts_dir = project_root / ".specify" / "extensions"
    if exts_dir.is_dir():
        for ext_dir in sorted(exts_dir.iterdir()):
            cmds_dir = ext_dir / "commands"
            if cmds_dir.is_dir():
                for f in cmds_dir.glob("*.md"):
                    if f.stem == command_name:
                        return f, ext_dir.name
    # 3. Check core templates
    core = project_root / ".specify" / "templates" / "commands"
    if core.is_dir():
        stem = command_name.replace("speckit.", "").replace("spec.", "")
        candidate = core / f"{stem}.md"
        if candidate.exists():
            return candidate, None
    return None, None


def _extract_script_path(template_path, project_root, ext_id):
    content = template_path.read_text(encoding="utf-8")
    m = re.match(r'^---\\n(.*?)\\n---', content, re.DOTALL)
    if not m:
        return None
    fm = m.group(1)
    scripts_m = re.search(r'scripts:\\s*\\n((?:\\s+\\w+:.*\\n)*)', fm)
    if not scripts_m:
        return None
    variants = {}
    for line in scripts_m.group(1).strip().splitlines():
        kv = re.match(r'\\s+(\\w+):\\s*(.+)', line)
        if kv:
            variants[kv.group(1)] = kv.group(2).strip().strip('"\\'')
    default = "ps" if platform.system().lower().startswith("win") else "sh"
    script_rel = variants.get(default) or variants.get("sh") or variants.get("py")
    if not script_rel:
        return None
    if ext_id:
        script_abs = project_root / ".specify" / "extensions" / ext_id / script_rel
    else:
        script_abs = project_root / ".specify" / script_rel
    return str(script_abs) if script_abs.exists() else None


def main():
    if len(sys.argv) < 3:
        sys.exit(0)
    command_name = sys.argv[1]
    event_name = sys.argv[2]
    project_root = _project_root()
    payload = sys.stdin.read() if not sys.stdin.isatty() else "{}"
    template, ext_id = _find_command_template(command_name, project_root)
    if not template:
        sys.exit(0)
    script_path = _extract_script_path(template, project_root, ext_id)
    if not script_path:
        sys.exit(0)
    try:
        result = subprocess.run(
            [script_path], input=payload, capture_output=True, text=True, timeout=120,
        )
        if result.stdout:
            print(result.stdout, end="")
        if result.returncode != 0:
            if result.stderr:
                print(result.stderr, file=sys.stderr, end="")
            sys.exit(2)
        sys.exit(0)
    except subprocess.TimeoutExpired:
        print(f"Hook {command_name} timed out", file=sys.stderr)
        sys.exit(2)
    except Exception as e:
        print(f"Hook {command_name} error: {e}", file=sys.stderr)
        sys.exit(2)


if __name__ == "__main__":
    main()
'''

# -- TS plugin template (opencode) ----------------------------------------

_TS_PLUGIN_TEMPLATE = '''import {{ execSync }} from 'child_process';
import * as path from 'path';

const BRIDGE = path.join(process.cwd(), '.specify', 'hooks', 'bridge.py');

function runHook(command: string, event: string, input: any): void {{
  try {{
    execSync(`python3 ${{BRIDGE}} ${{command}} ${{event}}`, {{
      input: JSON.stringify(input),
      stdio: ['pipe', 'inherit', 'inherit'],
      timeout: 60000,
    }});
  }} catch (e) {{
    process.exit(2);
  }}
}}

{hook_entries}

export default (async ({{ client, project, directory, $ }}) => {{
  return {{
{plugin_returns}
  }};
}});
'''


# -- Hook resolution -------------------------------------------------------

def resolve_hooks(
    integration_key: str,
    integration_config: dict[str, Any] | None,
    project_root: Path,
    parsed_options: dict[str, Any] | None,
) -> dict[str, dict[str, Any]]:
    """Resolve the final hook set for an integration.

    Layer 1: ``--hooks false`` → return ``{}``
    Layer 2: ``.specify/integration-hooks.yml`` → replace entirely if key present
    Layer 3: extension-declared ``runtime_hooks:`` → appended
    Layer 4: ``config["hooks"]`` → built-in baseline
    """
    # Layer 1: CLI flag gate
    if parsed_options:
        hooks_flag = str(parsed_options.get("hooks", "true")).lower()
        if hooks_flag in ("false", "0", "no", "off"):
            return {}

    # Layer 4: built-in defaults from integration config
    hooks: dict[str, dict[str, Any]] = {}
    if integration_config and isinstance(integration_config.get("hooks"), dict):
        hooks = dict(integration_config["hooks"])

    # Layer 3: extension-declared runtime hooks
    ext_hooks = collect_extension_runtime_hooks(project_root)
    hooks.update(ext_hooks)

    # Layer 2: user YAML override (replaces entirely if key present)
    override_file = project_root / YAML_OVERRIDE_FILENAME
    if override_file.exists():
        try:
            override = yaml.safe_load(override_file.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError:
            logger.warning("Could not parse %s; ignoring override", override_file)
            override = {}
        integrations = override.get("integrations", {}) if isinstance(override, dict) else {}
        if integration_key in integrations:
            key_data = integrations[integration_key]
            if isinstance(key_data, dict):
                hooks = key_data.get("hooks", {}) or {}
            else:
                hooks = {}

    return hooks


def collect_extension_runtime_hooks(project_root: Path) -> dict[str, dict[str, Any]]:
    """Scan all installed extensions for ``runtime_hooks:`` declarations."""
    hooks: dict[str, dict[str, Any]] = {}
    exts_dir = project_root / ".specify" / "extensions"
    if not exts_dir.is_dir():
        return hooks

    for ext_dir in sorted(exts_dir.iterdir()):
        if not ext_dir.is_dir():
            continue
        ext_yml = ext_dir / "extension.yml"
        if not ext_yml.exists():
            continue
        try:
            data = yaml.safe_load(ext_yml.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError:
            continue
        if not isinstance(data, dict):
            continue
        runtime = data.get("runtime_hooks", {}) or {}
        if not isinstance(runtime, dict):
            continue
        for event, config in runtime.items():
            if isinstance(config, dict):
                hooks[event] = config
    return hooks


# -- Adapter infrastructure ------------------------------------------------

class HookAdapter(ABC):
    """Abstract base for per-agent native hook config generation/merge.

    Subclasses set ``CANONICAL_TO_NATIVE`` to map canonical event names
    (e.g. ``PreToolUse``) to the agent's native event names. Events not
    in the mapping are silently skipped with a warning at install time.
    """

    # Maps canonical event name → agent-native event name.
    # Empty dict means no events are supported (adapter is a no-op).
    CANONICAL_TO_NATIVE: dict[str, str] = {}

    @property
    @abstractmethod
    def config_file_rel(self) -> str:
        """Project-relative path to the native settings file."""

    @abstractmethod
    def generate_fragment(self, hooks: dict[str, dict[str, Any]], project_root: Path) -> tuple[str, Any]:
        """Return (format, fragment) where format is 'json' or 'toml'."""

    @abstractmethod
    def merge_fragment(self, dst: Path, fragment: Any, *, format: str) -> None:
        """Merge fragment into the native config file at *dst*."""

    @abstractmethod
    def remove_entries(self, dst: Path) -> None:
        """Remove all Specify-authored hook entries from *dst*."""

    def _native_event(self, canonical: str) -> str | None:
        """Return the native event name for a canonical name, or None."""
        return self.CANONICAL_TO_NATIVE.get(canonical)

    def _filter_hooks(self, hooks: dict[str, dict[str, Any]]) -> dict[str, dict[str, Any]]:
        """Filter hooks to only those supported by this adapter.

        Prints a warning for each unsupported event and returns a dict
        containing only the supported ones.
        """
        import sys
        filtered: dict[str, dict[str, Any]] = {}
        for event, config in hooks.items():
            if self._native_event(event) is not None:
                filtered[event] = config
            else:
                adapter_name = type(self).__name__
                print(
                    f"\u26a0\ufe0f  {adapter_name} does not support '{event}' events; skipping",
                    file=sys.stderr,
                )
        return filtered

    def install(
        self,
        project_root: Path,
        manifest: "IntegrationManifest",
        hooks: dict[str, dict[str, Any]],
    ) -> list[Path]:
        """Generate bridge, merge native config, return created files."""
        # Filter to only events this adapter supports
        hooks = self._filter_hooks(hooks)
        if not hooks:
            return []

        created: list[Path] = []

        # Generate bridge script
        bridge_dir = project_root / HOOK_BRIDGE_DIR
        bridge_dir.mkdir(parents=True, exist_ok=True)
        bridge_path = bridge_dir / HOOK_BRIDGE_FILENAME
        bridge_path.write_text(_BRIDGE_TEMPLATE, encoding="utf-8")
        bridge_path.chmod(0o755)
        manifest.record_file(
            str(bridge_path.relative_to(project_root)),
            bridge_path.read_bytes(),
        )
        created.append(bridge_path)

        # Generate / merge native config
        config_path = project_root / self.config_file_rel
        fmt, fragment = self.generate_fragment(hooks, project_root)
        self.merge_fragment(config_path, fragment, format=fmt)

        # Record or mark as existing
        if config_path.exists():
            rel = str(config_path.relative_to(project_root))
            if rel not in manifest.files:
                manifest.record_existing(rel)

        created.append(config_path)
        return created

    def remove(self, project_root: Path, manifest: "IntegrationManifest") -> None:
        """Remove Specify-authored entries from native config."""
        config_path = project_root / self.config_file_rel
        if config_path.exists():
            self.remove_entries(config_path)


class JSONHookAdapter(HookAdapter):
    """Base for agents using JSON settings files.

    Subclasses set ``config_file_rel``, ``CANONICAL_TO_NATIVE``, and
    optionally ``bridge_path_prefix`` (e.g. ``${CLAUDE_PROJECT_DIR}/``).
    The default ``_build_fragment()`` produces Claude-style nested
    matcher-groups. Override for different JSON structures (e.g. Cursor's
    flat format).
    """

    config_file_rel: str = ""
    bridge_path_prefix: str = ""

    def generate_fragment(self, hooks: dict[str, dict[str, Any]], project_root: Path) -> tuple[str, Any]:
        fragment = self._build_fragment(hooks, project_root)
        return "json", fragment

    @abstractmethod
    def _build_fragment(self, hooks: dict[str, dict[str, Any]], project_root: Path) -> dict:
        ...

    def _build_nested_fragment(self, hooks: dict[str, dict[str, Any]], project_root: Path) -> dict:
        """Build Claude-style nested matcher-groups fragment.

        Shared by Claude, Qwen, Devin, Gemini, Tabnine — all use the same
        nested ``hooks.{Event}[].{matcher, hooks[]}`` structure.
        """
        result: dict[str, list] = {"hooks": {}}
        for event, config in hooks.items():
            native = self._native_event(event)
            if native is None:
                continue
            matcher = config.get("matcher", "*")
            timeout = config.get("timeout", 60)
            command = config.get("command", "")
            entry = {
                "type": "command",
                "command": "python3",
                "args": [
                    self.bridge_path_prefix + HOOK_BRIDGE_REL,
                    command,
                    event,
                ],
                "timeout": timeout,
                _SPECKIT_MARKER: True,
            }
            result["hooks"][native] = [{
                "matcher": matcher,
                "hooks": [entry],
            }]
        return result

    def merge_fragment(self, dst: Path, fragment: Any, *, format: str) -> None:
        if format != "json":
            return
        existing: dict = {}
        if dst.exists():
            try:
                existing = json.loads(dst.read_text(encoding="utf-8"))
                if not isinstance(existing, dict):
                    existing = {}
            except (json.JSONDecodeError, OSError):
                logger.warning("Could not parse %s; skipping merge", dst)
                return

        # Merge: only touch the "hooks" key
        existing_hooks = existing.get("hooks", {})
        our_hooks = fragment.get("hooks", {})

        for event, entries in our_hooks.items():
            existing_list = existing_hooks.get(event, [])
            if not isinstance(existing_list, list):
                existing_list = []
            # Remove our old entries for this event (by marker), then append new
            existing_list = [e for e in existing_list if not _has_marker(e)]
            existing_list.extend(entries)
            existing_hooks[event] = existing_list

        existing["hooks"] = existing_hooks
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(json.dumps(existing, indent=2) + "\n", encoding="utf-8")

    def remove_entries(self, dst: Path) -> None:
        try:
            existing = json.loads(dst.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return
        if not isinstance(existing, dict):
            return
        hooks = existing.get("hooks", {})
        if not isinstance(hooks, dict):
            return
        cleaned: dict[str, list] = {}
        for event, entries in hooks.items():
            if not isinstance(entries, list):
                continue
            kept_entries = []
            for entry in entries:
                if not isinstance(entry, dict):
                    kept_entries.append(entry)
                    continue
                # Claude nested format: entry has "hooks" list
                inner = entry.get("hooks")
                if isinstance(inner, list):
                    kept_inner = [h for h in inner if not _has_marker(h)]
                    if kept_inner:
                        entry["hooks"] = kept_inner
                        kept_entries.append(entry)
                    # else: drop the entire matcher-group (all our hooks)
                elif _has_marker(entry):
                    pass  # drop this flat entry (Cursor format)
                else:
                    kept_entries.append(entry)
            if kept_entries:
                cleaned[event] = kept_entries
        if cleaned:
            existing["hooks"] = cleaned
        else:
            existing.pop("hooks", None)
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(json.dumps(existing, indent=2) + "\n", encoding="utf-8")


class ClaudeHookAdapter(JSONHookAdapter):
    """Claude Code: nested matcher-groups in .claude/settings.json."""

    config_file_rel = ".claude/settings.json"
    bridge_path_prefix = "${CLAUDE_PROJECT_DIR}/"
    CANONICAL_TO_NATIVE = {
        "PreToolUse": "PreToolUse",
        "PostToolUse": "PostToolUse",
        "Stop": "Stop",
        "SessionStart": "SessionStart",
        "SessionEnd": "SessionEnd",
        "UserPromptSubmit": "UserPromptSubmit",
    }

    def _build_fragment(self, hooks: dict[str, dict[str, Any]], project_root: Path) -> dict:
        return self._build_nested_fragment(hooks, project_root)


class CursorHookAdapter(JSONHookAdapter):
    """Cursor: flat handler arrays in .cursor/hooks.json."""

    config_file_rel = ".cursor/hooks.json"
    CANONICAL_TO_NATIVE = {
        "PreToolUse": "preToolUse",
        "PostToolUse": "postToolUse",
        "Stop": "stop",
        "SessionStart": "sessionStart",
        "SessionEnd": "sessionEnd",
        "UserPromptSubmit": "beforeSubmitPrompt",
    }

    def _build_fragment(self, hooks: dict[str, dict[str, Any]], project_root: Path) -> dict:
        result: dict[str, list] = {"hooks": {}}
        for event, config in hooks.items():
            native = self._native_event(event)
            if native is None:
                continue
            matcher = config.get("matcher", "*")
            timeout = config.get("timeout", 60)
            command = config.get("command", "")
            entry = {
                "command": f"python3 {HOOK_BRIDGE_REL} {command} {event}",
                "type": "command",
                "timeout": timeout,
                "matcher": matcher,
                _SPECKIT_MARKER: True,
            }
            result["hooks"][native] = [entry]
        return result


class CodexHookAdapter(HookAdapter):
    """Codex CLI: TOML [[hooks.*]] in config.toml."""

    config_file_rel = ".codex/config.toml"
    CANONICAL_TO_NATIVE = {
        "PreToolUse": "PreToolUse",
        "PostToolUse": "PostToolUse",
        "Stop": "Stop",
        "SessionStart": "SessionStart",
        "SessionEnd": "SessionEnd",
        "UserPromptSubmit": "UserPromptSubmit",
    }

    def generate_fragment(self, hooks: dict[str, dict[str, Any]], project_root: Path) -> tuple[str, Any]:
        lines: list[str] = []
        for event, config in hooks.items():
            native = self._native_event(event)
            if native is None:
                continue
            matcher = config.get("matcher", "*")
            timeout = config.get("timeout", 60)
            command = config.get("command", "")
            bridge_abs = f"$(git rev-parse --show-toplevel)/{HOOK_BRIDGE_REL}"
            lines.append(f'[[hooks.{native}]]')
            lines.append(f'matcher = "{matcher}"')
            lines.append('')
            lines.append(f'[[hooks.{native}.hooks]]')
            lines.append('type = "command"')
            lines.append(f'command = \'python3 {bridge_abs} {command} {event}\'')
            lines.append(f'timeout = {timeout}')
            lines.append('speckit_marker = true')
            lines.append('')
        return "toml", "\n".join(lines)

    def merge_fragment(self, dst: Path, fragment: Any, *, format: str) -> None:
        if format != "toml":
            return
        existing = ""
        if dst.exists():
            existing = dst.read_text(encoding="utf-8")
        # Remove old speckit-marked blocks
        existing = re.sub(
            r'\[\[hooks\.\w+\]\]\n(?:(?!\[\[hooks\.\w+\]\]).)*?speckit_marker = true\n*',
            "",
            existing,
            flags=re.DOTALL,
        )
        # Append new
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(existing.rstrip() + "\n\n" + fragment + "\n", encoding="utf-8")

    def remove_entries(self, dst: Path) -> None:
        if not dst.exists():
            return
        existing = dst.read_text(encoding="utf-8")
        cleaned = re.sub(
            r'\[\[hooks\.\w+\]\]\n(?:(?!\[\[hooks\.\w+\]\]).)*?speckit_marker = true\n*',
            "",
            existing,
            flags=re.DOTALL,
        )
        dst.write_text(cleaned, encoding="utf-8")


class OpencodeHookAdapter(HookAdapter):
    """opencode: TypeScript plugin in .opencode/plugin/ + opencode.json merge."""

    config_file_rel = "opencode.json"
    _PLUGIN_REL = ".opencode/plugin/speckit-hooks.ts"
    CANONICAL_TO_NATIVE = {
        "PreToolUse": "tool.execute.before",
        "PostToolUse": "tool.execute.after",
    }

    def install(
        self,
        project_root: Path,
        manifest: "IntegrationManifest",
        hooks: dict[str, dict[str, Any]],
    ) -> list[Path]:
        # Filter to only events this adapter supports
        hooks = self._filter_hooks(hooks)
        if not hooks:
            return []

        created: list[Path] = []

        # Generate bridge script
        bridge_dir = project_root / HOOK_BRIDGE_DIR
        bridge_dir.mkdir(parents=True, exist_ok=True)
        bridge_path = bridge_dir / HOOK_BRIDGE_FILENAME
        bridge_path.write_text(_BRIDGE_TEMPLATE, encoding="utf-8")
        bridge_path.chmod(0o755)
        manifest.record_file(
            str(bridge_path.relative_to(project_root)),
            bridge_path.read_bytes(),
        )
        created.append(bridge_path)

        # Generate TS plugin
        plugin_path = project_root / self._PLUGIN_REL
        plugin_path.parent.mkdir(parents=True, exist_ok=True)
        plugin_path.write_text(self._build_plugin(hooks), encoding="utf-8")
        manifest.record_file(
            str(plugin_path.relative_to(project_root)),
            plugin_path.read_bytes(),
        )
        created.append(plugin_path)

        # Merge plugin path into opencode.json
        config_path = project_root / self.config_file_rel
        self._merge_plugin_ref(config_path)
        rel = str(config_path.relative_to(project_root))
        if rel not in manifest.files:
            manifest.record_existing(rel)

        created.append(config_path)
        return created

    def generate_fragment(self, hooks: dict[str, dict[str, Any]], project_root: Path) -> tuple[str, Any]:
        return "skip", None

    def merge_fragment(self, dst: Path, fragment: Any, *, format: str) -> None:
        pass

    def remove_entries(self, dst: Path) -> None:
        if not dst.exists():
            return
        try:
            existing = json.loads(dst.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return
        if not isinstance(existing, dict):
            return
        plugins = existing.get("plugin", [])
        if isinstance(plugins, list):
            plugins = [p for p in plugins if p != f"./{self._PLUGIN_REL}"]
            if plugins:
                existing["plugin"] = plugins
            else:
                existing.pop("plugin", None)
            dst.write_text(json.dumps(existing, indent=2) + "\n", encoding="utf-8")

    def _build_plugin(self, hooks: dict[str, dict[str, Any]]) -> str:
        hook_entries: list[str] = []
        plugin_returns: list[str] = []
        for event, config in hooks.items():
            native = self._native_event(event)
            if native is None:
                continue
            command = config.get("command", "")
            matcher = config.get("matcher", "*")
            ts_hook = native  # already "tool.execute.before" etc.
            match_cond = ""
            if matcher and matcher != "*":
                tools = [t.strip().strip('"') for t in matcher.split("|")]
                checks = " || ".join(f"input.tool === '{t.lower()}'" for t in tools)
                match_cond = f"if ({checks}) {{"
            else:
                match_cond = "{"
            hook_entries.append(
                f"function _{event}(input: any) {match_cond}\n"
                f"    runHook('{command}', '{event}', input);\n"
                f"  }}"
            )
            plugin_returns.append(
                f"    \"{ts_hook}\": async (input: any, output: any) => {{\n"
                f"      _{event}(input);\n"
                f"    }},"
            )
        return _TS_PLUGIN_TEMPLATE.format(
            hook_entries="\n\n".join(hook_entries),
            plugin_returns="\n".join(plugin_returns),
        )

    def _merge_plugin_ref(self, config_path: Path) -> None:
        existing: dict = {}
        if config_path.exists():
            try:
                existing = json.loads(config_path.read_text(encoding="utf-8"))
                if not isinstance(existing, dict):
                    existing = {}
            except (json.JSONDecodeError, OSError):
                return
        plugins = existing.get("plugin", [])
        if not isinstance(plugins, list):
            plugins = []
        ref = f"./{self._PLUGIN_REL}"
        if ref not in plugins:
            plugins.append(ref)
        existing["plugin"] = plugins
        config_path.write_text(json.dumps(existing, indent=2) + "\n", encoding="utf-8")


# -- Phase 1: JSON config-file adapters (nested matcher-groups) ------------

class QwenHookAdapter(JSONHookAdapter):
    """Qwen Code: nested matcher-groups in .qwen/settings.json.

    Qwen uses the same event names and JSON structure as Claude Code.
    """

    config_file_rel = ".qwen/settings.json"
    CANONICAL_TO_NATIVE = {
        "PreToolUse": "PreToolUse",
        "PostToolUse": "PostToolUse",
        "Stop": "Stop",
        "SessionStart": "SessionStart",
        "SessionEnd": "SessionEnd",
        "UserPromptSubmit": "UserPromptSubmit",
    }

    def _build_fragment(self, hooks: dict[str, dict[str, Any]], project_root: Path) -> dict:
        return self._build_nested_fragment(hooks, project_root)


class GeminiHookAdapter(JSONHookAdapter):
    """Gemini CLI: nested matcher-groups in .gemini/settings.json.

    Gemini uses different event names (BeforeTool, AfterTool, AfterAgent).
    """

    config_file_rel = ".gemini/settings.json"
    CANONICAL_TO_NATIVE = {
        "PreToolUse": "BeforeTool",
        "PostToolUse": "AfterTool",
        "Stop": "AfterAgent",
        "SessionStart": "SessionStart",
        "SessionEnd": "SessionEnd",
    }

    def _build_fragment(self, hooks: dict[str, dict[str, Any]], project_root: Path) -> dict:
        return self._build_nested_fragment(hooks, project_root)


class DevinHookAdapter(JSONHookAdapter):
    """Devin for Terminal: hooks in .devin/hooks.v1.json.

    Devin uses the same event names and JSON structure as Claude Code.
    Also reads .claude/settings.json for compatibility, but we write to
    the native format for independence.
    """

    config_file_rel = ".devin/hooks.v1.json"
    CANONICAL_TO_NATIVE = {
        "PreToolUse": "PreToolUse",
        "PostToolUse": "PostToolUse",
        "Stop": "Stop",
        "SessionStart": "SessionStart",
        "SessionEnd": "SessionEnd",
        "UserPromptSubmit": "UserPromptSubmit",
    }

    def _build_fragment(self, hooks: dict[str, dict[str, Any]], project_root: Path) -> dict:
        return self._build_nested_fragment(hooks, project_root)


class TabnineHookAdapter(JSONHookAdapter):
    """Tabnine CLI: nested matcher-groups in .tabnine/agent/settings.json.

    Tabnine uses different event names (BeforeTool, AfterTool), like Gemini.
    """

    config_file_rel = ".tabnine/agent/settings.json"
    CANONICAL_TO_NATIVE = {
        "PreToolUse": "BeforeTool",
        "PostToolUse": "AfterTool",
        "SessionStart": "SessionStart",
        "SessionEnd": "SessionEnd",
    }

    def _build_fragment(self, hooks: dict[str, dict[str, Any]], project_root: Path) -> dict:
        return self._build_nested_fragment(hooks, project_root)


# -- Adapter registry -----------------------------------------------------

_ADAPTERS: dict[str, type[HookAdapter]] = {
    "claude": ClaudeHookAdapter,
    "cursor-agent": CursorHookAdapter,
    "codex": CodexHookAdapter,
    "opencode": OpencodeHookAdapter,
    "qwen": QwenHookAdapter,
    "gemini": GeminiHookAdapter,
    "devin": DevinHookAdapter,
    "tabnine": TabnineHookAdapter,
}


def resolve_adapter(integration_key: str) -> HookAdapter | None:
    """Return a hook adapter for the integration key, or None if unsupported."""
    cls = _ADAPTERS.get(integration_key)
    return cls() if cls else None


# -- Public entry points (called from IntegrationBase) --------------------

def install_integration_hooks(
    integration: "IntegrationBase",
    project_root: Path,
    manifest: "IntegrationManifest",
    parsed_options: dict[str, Any] | None = None,
) -> list[Path]:
    """Install runtime hooks for an integration.

    Called from ``IntegrationBase.setup()`` after commands are written.
    Returns list of created/managed files. No-ops gracefully when hooks
    are disabled or the agent has no adapter.
    """
    adapter = resolve_adapter(integration.key)
    if adapter is None:
        return []

    hooks = resolve_hooks(
        integration.key,
        integration.config,
        project_root,
        parsed_options,
    )
    if not hooks:
        # Hooks disabled or empty — clean up any previous hooks
        remove_integration_hooks(integration, project_root, manifest)
        return []

    # Remove old hooks before installing new ones so stale events
    # from a previous install/upgrade are cleaned up.
    remove_integration_hooks(integration, project_root, manifest)

    return adapter.install(project_root, manifest, hooks)


def remove_integration_hooks(
    integration: "IntegrationBase",
    project_root: Path,
    manifest: "IntegrationManifest",
) -> None:
    """Remove runtime hooks for an integration.

    Called from ``IntegrationBase.teardown()`` before manifest uninstall.
    Removes only Specify-authored entries from native config files.
    """
    adapter = resolve_adapter(integration.key)
    if adapter is None:
        return

    adapter.remove(project_root, manifest)

    # Remove bridge script if tracked
    bridge_rel = HOOK_BRIDGE_REL
    if bridge_rel in manifest.files:
        bridge_path = project_root / bridge_rel
        if bridge_path.exists():
            bridge_path.unlink(missing_ok=True)
        manifest.remove(bridge_rel)

    # Remove opencode TS plugin if tracked
    if integration.key == "opencode":
        plugin_rel = str(OpencodeHookAdapter._PLUGIN_REL)
        if plugin_rel in manifest.files:
            plugin_path = project_root / plugin_rel
            if plugin_path.exists():
                plugin_path.unlink(missing_ok=True)
            manifest.remove(plugin_rel)


def hooks_stale_exclusions(integration_key: str) -> set[str]:
    """Return project-relative paths to protect from stale cleanup."""
    adapter = resolve_adapter(integration_key)
    if adapter is None:
        return set()
    exclusions = {adapter.config_file_rel}
    if integration_key == "opencode":
        exclusions.add(OpencodeHookAdapter._PLUGIN_REL)
    return exclusions


# -- Helpers ---------------------------------------------------------------

def _has_marker(entry: Any) -> bool:
    """Check if a JSON hook entry has the Specify marker."""
    if isinstance(entry, dict):
        return entry.get(_SPECKIT_MARKER, False) is True
    return False


def _to_camel_case(snake_or_pascal: str) -> str:
    """Convert PascalCase or snake_case to camelCase."""
    if not snake_or_pascal:
        return snake_or_pascal
    first = snake_or_pascal[0].lower()
    rest = snake_or_pascal[1:]
    # Handle PascalCase: PreToolUse -> preToolUse
    return first + rest


# -- Extension manifest validation callout ---------------------------------

def validate_runtime_hooks(data: dict[str, Any]) -> None:
    """Validate ``runtime_hooks`` field in extension manifest data.

    Called from ``ExtensionManifest._validate()`` via a callout.
    Raises ``ValidationError`` if ``runtime_hooks`` is present but malformed.
    """
    from ..extensions import ValidationError

    runtime_hooks = data.get("runtime_hooks")
    if "runtime_hooks" in data and not isinstance(runtime_hooks, dict):
        raise ValidationError("Invalid runtime_hooks: expected a mapping")
    if runtime_hooks:
        for hook_name, hook_config in runtime_hooks.items():
            if not isinstance(hook_config, dict):
                raise ValidationError(
                    f"Invalid runtime_hook '{hook_name}': expected a mapping"
                )
            if not hook_config.get("command"):
                raise ValidationError(
                    f"Runtime hook '{hook_name}' missing required 'command' field"
                )
            if hook_name not in CANONICAL_RUNTIME_EVENTS:
                raise ValidationError(
                    f"Unknown runtime_hook '{hook_name}': "
                    f"must be one of {sorted(CANONICAL_RUNTIME_EVENTS)}"
                )


def has_runtime_hooks(data: dict[str, Any]) -> bool:
    """Return True if ``runtime_hooks`` is present and non-empty."""
    return bool(data.get("runtime_hooks"))
